// Fonte única: gera os PDFs (scripts/gerar-pdf.cjs) e a página no site, nos 3 idiomas.
import type { DocumentoAxioma, DocTrilingue } from "../tipos"

const pt: DocumentoAxioma = {
  arquivo: '00 - Prólogo, Apresentação e Primeiros Passos.docx',
  titulo: 'Manual 00 — Prólogo e Apresentação',
  subtitulo: 'O que significa Axioma, o que é a plataforma, como pensa o seu motor de inteligência e tudo o que é igual em todas as telas',
  info: ['Manual de uso do Axioma AI.Tech  •  Versão 2.0'],
  blocos: [
    { h1: 'Prólogo — o que significa "Axioma"' },
    { h2: 'A origem da palavra' },
    { p: 'A palavra **axioma** vem do grego antigo **ἀξίωμα (axíōma)**, que significa "aquilo que é considerado digno", "aquilo que se recomenda por si mesmo como evidente". Ela deriva do verbo **ἀξιόω (axióō)**, "considerar digno", "julgar válido", que por sua vez nasce de **ἄξιος (áxios)**: "que tem valor", "que está em equilíbrio", "que pesa o mesmo que". É a imagem de uma balança em equilíbrio, em que algo vale exatamente o que diz valer.' },
    { p: 'Na origem, portanto, axioma é aquilo que **tem valor próprio** e **sustenta todo o resto**.' },
    { h2: 'O axioma na ciência' },
    { p: 'Na filosofia grega, **Aristóteles** (século IV a.C.) usou o termo como conceito técnico da lógica: axiomas são as proposições imediatas que é preciso conhecer para aprender qualquer outra coisa, os pontos de partida de toda demonstração. Pouco depois, **Euclides de Alexandria**, nos *Elementos* (cerca de 300 a.C.), construiu toda a geometria a partir de um pequeno conjunto de axiomas e postulados. Dessas poucas verdades de base, por dedução rigorosa, nascem centenas de teoremas.' },
    { p: 'Na matemática e na lógica modernas, a partir de **David Hilbert** (início do século XX), o axioma passou a ser entendido como a **premissa fundamental de um sistema formal**: uma regra de partida, clara e explícita, da qual todo o resto é derivado de forma verificável. A aritmética, a teoria dos conjuntos e a própria ciência da computação se apoiam em sistemas axiomáticos: poucas bases sólidas, raciocínio rigoroso e conclusões que qualquer pessoa pode conferir.' },
    { nota: '**Em resumo:** um axioma é um ponto de partida confiável. Quando as bases são sólidas e o raciocínio é rigoroso, as conclusões também são.' },
    { h2: 'Por que a plataforma se chama Axioma' },
    { p: 'Uma empresa também precisa de axiomas: **números verdadeiros** sobre o que entra, o que sai, o que se deve e o que se tem a receber. Sem eles, toda decisão é um palpite. O Axioma foi construído sobre essa ideia:' },
    { lista: [
      '**Os números são a base, e são reais.** Cada cálculo parte dos lançamentos, documentos e extratos da própria empresa. Nenhum dado fictício é misturado aos seus.',
      '**O raciocínio é rigoroso e conferível.** Impostos, totais, projeções e indicadores são calculados por regras fixas e auditáveis, não por adivinhação.',
      '**A inteligência interpreta, nunca inventa.** A inteligência artificial explica os números e sugere caminhos, e cada valor que ela cita é conferido contra os dados da empresa.',
      '**Os seus dados são seus.** A privacidade e a segurança das informações da empresa e das pessoas vêm antes de qualquer funcionalidade.',
    ] },
    { p: 'Assim como Euclides partiu de poucas verdades para construir toda a geometria, o Axioma parte dos números reais da sua empresa para construir a visão completa do negócio.' },

    { h1: 'Apresentação — a plataforma' },
    { p: 'O **Axioma AI.Tech** é um **CFO digital**: uma plataforma de gestão financeira, contábil e de inteligência empresarial que reúne em um só lugar tudo o que um diretor financeiro e um contador acompanham (receitas, custos, caixa, resultado, dívidas, impostos, lançamentos contábeis, clientes, fornecedores, estoque, metas, investimentos e o cenário econômico) e transforma esses dados em decisões.' },
    { p: 'Ele foi pensado para a realidade das empresas brasileiras, do Microempreendedor Individual à empresa de médio porte, e funciona em português, inglês e espanhol.' },
    { h2: 'Nosso objetivo' },
    { p: 'A maioria das pequenas e médias empresas não tem acesso a um diretor financeiro. Decisões importantes, como quanto cobrar, quando contratar, se cabe um empréstimo ou como pagar menos imposto dentro da lei, acabam sendo tomadas no escuro. O objetivo do Axioma é **colocar a inteligência de um CFO experiente ao alcance de qualquer empresa**, disponível a qualquer hora, com os números reais do negócio, em linguagem simples e com respeito total à privacidade de quem usa.' },
    { p: 'Cada tela do Axioma segue o mesmo princípio: mostrar **o que está acontecendo, por que está acontecendo e qual é o próximo passo**.' },

    { h1: 'Inovação: o melhor da tecnologia mundial, pensado para o Brasil' },
    { p: 'O Axioma acompanha de perto o que há de mais avançado em gestão financeira e inteligência artificial nos grandes polos de tecnologia do mundo e traz essas ideias para a realidade da empresa brasileira, com as nossas leis, os nossos impostos e o nosso sistema bancário.' },
    { tabela: { colunas: ['Referência', 'O que inspira', 'Como aparece no Axioma'], larguras: [1900, 3300, 3826], linhas: [
      ['China', 'Plataformas que integram vendas, pagamentos instantâneos e gestão no mesmo lugar, e o uso intenso de dados em tempo real.', 'PDV integrado ao estoque e ao financeiro; pagamento de contas por Pix dentro da plataforma (em preparação); painéis que se atualizam com os dados do dia.'],
      ['Europa', 'Open Banking (com a diretiva PSD2) e privacidade desde a concepção (privacy by design, inspirada na GDPR).', 'Conexão bancária por Open Finance com consentimento do titular; isolamento dos dados por empresa; auditoria do uso de IA sem guardar conteúdo; regras de prazo e lixeira para dados pessoais.'],
      ['Estados Unidos', 'Modelos de linguagem de última geração e ferramentas de planejamento financeiro com IA (FP&A).', 'Motor de orquestração de IA em camadas, com especialistas por área e por setor, conferência automática de números, análises executivas e planos de longo prazo do José.'],
    ] } },
    { h2: 'Funções que levam a gestão além do convencional' },
    { lista: [
      '**Conferência automática de números da IA:** cada valor citado pela inteligência é checado contra os dados reais da empresa antes de chegar a você.',
      '**Nexus e o José:** leitura diária da economia do Brasil e do mundo a partir de fontes públicas oficiais (como Banco Central, IBGE, Banco Mundial e OCDE), cruzada com o setor da sua empresa, com um placar que compara o que foi previsto com o que de fato aconteceu.',
      '**Gêmeo digital do caixa:** simulação do caixa da empresa para testar decisões antes de tomá-las (Tesouraria).',
      '**Leitura inteligente de notas fiscais:** XML, PDF ou foto viram lançamentos distribuídos nos módulos certos, sempre com conferência humana antes de gravar.',
      '**Equipe com hierarquia e prazos:** convites presos a um e-mail, códigos de confirmação, acesso temporário e trilha de responsabilidade.',
      '**Assistente de Ajuda:** um chat em todas as telas que explica onde fica cada função e o que cada botão faz.',
      '**Tudo em três idiomas:** português, inglês e espanhol em todas as telas, nos manuais, nos Termos e na Política de Privacidade.',
    ] },
    { p: 'Nosso compromisso é seguir pesquisando e incorporando inovações sempre que elas tragam ganho real para a empresa, sem abrir mão da segurança e da privacidade de quem usa.' },

    { h1: 'O motor de inteligência do Axioma' },
    { p: 'O coração da plataforma é um **motor de orquestração de inteligência artificial**: um "cérebro" único, usado por todas as telas, construído em camadas para responder como um diretor financeiro de verdade, com segurança e com custo controlado.' },
    { tabela: { colunas: ['Camada', 'O que faz', 'Usa IA?'], larguras: [2200, 5326, 1500], linhas: [
      ['0. Retrato da empresa', 'Reúne os números de todos os módulos: receita, custos pelo nome, impostos pelo regime, lucro, margem, ponto de equilíbrio, caixa, dívidas, contas a receber e a pagar, inadimplência, estoque e obrigações fiscais. Identifica o setor da empresa (toda a classificação CNAE) e gera os alertas da situação.', 'Não'],
      ['1. Triagem', 'Classifica a pergunta como rotina (um fato direto), análise (precisa de raciocínio) ou estratégia (decisão de longo prazo). Primeiro por regras fixas; só em caso de dúvida, por uma IA rápida.', 'Às vezes'],
      ['2. Executor', 'Leva a pergunta ao modelo de IA adequado à complexidade: rotina usa modelos rápidos; análises e estratégias usam os modelos mais avançados. Se a pergunta se mostrar mais difícil do que parecia, ela sobe de nível automaticamente.', 'Sim'],
      ['3. Consulta aos dados', 'Quando precisa de detalhe (por exemplo, as contas que vencem nesta semana ou os maiores devedores), a IA consulta os dados da empresa em modo somente leitura. Ela nunca altera nada.', 'Sim'],
      ['4. Conferência', 'Todo valor em reais citado na resposta é conferido contra os dados reais. O que não puder ser conferido é sinalizado na tela.', 'Não'],
    ] } },
    { h2: 'Especialistas por área e por setor' },
    { p: 'Para cada pergunta, o motor escolhe até três **manuais especialistas** (caixa, custos, precificação, dívida, tributário, cobrança, estoque, crescimento, vendas e economia) e o **manual do setor** da empresa, entre 40 setores que cobrem toda a classificação CNAE. Uma padaria e uma transportadora recebem orientações diferentes, porque o que pesa no caixa de cada uma é diferente.' },
    { h2: 'Os assistentes que você vai encontrar' },
    { tabela: { colunas: ['Onde', 'O que faz'], larguras: [2600, 6426], linhas: [
      ['Assistente de Ajuda (botão Ajuda, canto inferior esquerdo)', 'Explica como usar o Axioma: onde fica cada função, o que cada botão faz, para onde leva e o passo a passo. Não vê os números da empresa.'],
      ['IA Financeira', 'Conversa sobre a saúde financeira da empresa: score, anomalias, projeções e planos de ação (Manual 36).'],
      ['IA Tributária', 'Compara regimes tributários e explica a carga de impostos e a Reforma Tributária com os seus números (Manual 37).'],
      ['José (Nexus)', 'Acompanha a economia do Brasil e do mundo, explica como cada acontecimento afeta o seu ramo e monta planos de 1 a 10 anos (Manual 43).'],
      ['IA MEI Advisor', 'Responde dúvidas do MEI sobre DAS, teto, imposto de renda e preço (Manual 08).'],
      ['Análises nos módulos', 'Os blocos "Pergunte ao Axioma CFO" e os botões de análise presentes em vários módulos geram uma análise executiva daquela tela.'],
      ['Leitura de notas', 'Lê notas fiscais em PDF ou foto, distribui os itens nos módulos certos e faz perguntas de conferência antes de gravar (Manual 33).'],
    ] } },
    { h2: 'Compromissos do motor com você' },
    { lista: [
      '**Nunca inventar número:** as contas são feitas pelo Axioma; a IA interpreta.',
      '**Privacidade em primeiro lugar:** a IA recebe só o necessário para responder; os provedores contratados não usam os seus dados para treinar modelos; o registro de auditoria guarda o uso, nunca o conteúdo das conversas.',
      '**Você decide:** a IA orienta e sugere; nenhuma decisão é tomada por ela em seu nome, e ela nunca grava, apaga ou paga nada sozinha.',
      '**Transparência de consumo:** a tela Config → Uso da IA mostra quantas perguntas foram feitas, quantos números foram conferidos e o custo.',
      '**Sempre funcionar:** se a IA estiver indisponível, as telas continuam respondendo com análises por regras.',
    ] },

    { h1: 'Como usar este manual' },
    { p: 'O manual é dividido em documentos numerados, um por módulo, na mesma ordem do menu do Axioma. Este primeiro apresenta a plataforma e explica o que é igual em todas as telas. Os seguintes explicam cada módulo em detalhe, sempre na mesma ordem de seções, para você achar a resposta rápido:' },
    { tabela: { colunas: ['Seção', 'O que responde'], larguras: [2800, 6226], linhas: [
      ['Para que serve', 'O problema que a tela resolve e quando usar.'],
      ['Como chegar', 'O caminho no menu e os atalhos de outras telas que levam até ela.'],
      ['Antes de começar', 'O que precisa estar cadastrado para a tela mostrar números certos.'],
      ['Mapa da tela', 'O que aparece de cima para baixo: cards, abas, gráficos e listas.'],
      ['Botões e ações', 'Cada botão: o que faz, para onde leva e o que acontece depois (se grava, se apaga, se dá para desfazer).'],
      ['Passo a passo', 'As tarefas mais comuns, numeradas.'],
      ['Ligações com outros módulos', 'De onde vêm os números e para onde eles vão.'],
      ['Quem pode fazer o quê', 'O que cada nível de acesso pode ver ou alterar.'],
      ['Problemas comuns e soluções', 'As dúvidas e os erros mais frequentes, com a solução.'],
    ] } },
    { p: 'O mesmo manual está dentro do Axioma, no botão **Manual** do menu do topo, e em PDF nos três idiomas. Se preferir perguntar, use o **Assistente de Ajuda** (seção mais abaixo).' },

    { h1: 'Primeiros passos' },
    { h2: 'Criar a conta e entrar' },
    { numerada: [
      'Acesse **axiomaai.com.br**. Na tela de entrada, clique em **Criar conta** (ou em **Cadastrar com Google**, para usar a sua conta Google).',
      'Informe nome, e-mail e uma senha. Confirme a verificação anti-robô (a caixinha da Cloudflare) quando ela aparecer.',
      'Confirme o e-mail pelo link ou código enviado para a sua caixa de entrada.',
      'Escolha um plano na tela **Planos** para liberar os módulos (Manual 40).',
      'Na primeira entrada, o Axioma cria automaticamente a sua empresa com o nome "Minha Empresa". Complete o cadastro em **Config → Empresa** (a faixa verde-menta no topo da tela lembra você disso e leva até lá com um clique).',
    ] },
    { nota: 'Esqueceu a senha? Na tela de entrada clique em **Esqueceu a senha?**. Você recebe um e-mail com um link para criar uma nova senha.' },
    { h2: 'Entrar por convite' },
    { numerada: [
      'Abra o link do convite que chegou no seu e-mail.',
      'Preencha o nome (e o CPF, quando o acesso for de mais de 30 dias ou sem prazo). Confira quem convidou você.',
      'Leia e aceite os Termos de Uso e a Política de Privacidade (LGPD).',
      'Clique em **Receber código no e-mail** e digite o código numérico que chegou. Ele prova que o e-mail é seu.',
      'Pronto: você entra direto na empresa que convidou, com o nível de acesso escolhido por quem convidou. Em alguns casos o acesso ainda precisa ser aprovado pelo dono ou administrador; a tela avisa.',
    ] },
    { h2: 'A ordem certa para começar' },
    { p: 'Para o Axioma mostrar números corretos desde o primeiro dia, siga esta ordem:' },
    { numerada: [
      '**Config → Empresa:** CNPJ, regime tributário (Simples, Presumido, Real ou MEI) e atividade (CNAE). Sem o regime, os impostos não podem ser calculados.',
      '**Financeiro → Custos Fixos:** aluguel, salários, sistemas, contador e tudo o que se repete todo mês.',
      '**Financeiro → Receitas:** as vendas e entradas (ou conecte o banco em **Open Finance**, ou use **Importar Documentos**).',
      '**Comercial → Clientes e Fornecedores:** quem compra e de quem você compra.',
      '**Comercial → Contas a Pagar e Contas a Receber:** o que vence nos próximos dias.',
      'Volte ao **Dashboard**: os números já aparecem cruzados.',
    ] },

    { h1: 'O menu do topo' },
    { p: 'O menu fica fixo no alto de todas as telas, como um tabuleiro de cartões em duas linhas. O cartão da seção em que você está fica aceso em verde-menta. Clique num grupo (os que têm a setinha ▼) para abrir a lista de telas dele:' },
    { tabela: { colunas: ['Cartão', 'O que tem dentro'], larguras: [2400, 6626], linhas: [
      ['Dashboard', 'Visão geral da empresa (Manual 01).'],
      ['Nexus', 'Inteligência de mercado com o assistente José (Manual 43).'],
      ['Financeiro ▼', 'Receitas, Custos Fixos, Custos Variáveis, Fluxo de Caixa, DRE, Endividamento, Tesouraria (Manuais 10 a 16).'],
      ['Contabilidade ▼', 'Contador, Fiscal, Livro Razão, Balancete, DRE Contábil (Manuais 17 a 21).'],
      ['Comercial ▼', 'Clientes, Fornecedores, Contas a Pagar, Estoque, Contas a Receber, Inadimplência (Manuais 26 a 31).'],
      ['Crescimento ▼', 'Metas, Investimentos, Simulações, Precificação (Manuais 22 a 25).'],
      ['Gestão ▼', 'Centros de Custo, Importar Documentos, Relatórios, Open Finance (Manuais 32 a 35).'],
      ['Equipe', 'Pessoas da empresa, convites e níveis de acesso (Manual 39).'],
      ['PT / EN / ES', 'Troca o idioma de todo o Axioma: português, inglês ou espanhol.'],
      ['MEI ▼ (PRO)', 'Painel MEI, Cockpit, Faturamento, DAS & Obrigações, Reforma Tributária, Precificação MEI, IA MEI Advisor, Imposto de Renda (Manuais 02 a 09).'],
      ['PDV (PRO)', 'Frente de caixa, produtos, retaguarda e entrada de NF-e (Manual 42).'],
      ['IA Premium ▼', 'IA Financeira e IA Tributária (Manuais 36 e 37).'],
      ['Config ▼', 'Empresa, Planos, Uso da IA e, para o dono, Equipe (Manuais 38 a 41).'],
      ['Manual', 'Este manual, dentro do Axioma, nos três idiomas.'],
      ['Termos de Uso / Privacidade', 'Os documentos legais, com troca de idioma.'],
      ['BANCO', 'Atalho para conectar o banco (Open Finance, Manual 35).'],
      ['Sair', 'Encerra a sua sessão com segurança.'],
    ] } },
    { p: 'No celular, o menu vira o botão **☰** no canto do topo, com os mesmos itens em lista.' },
    { nota: 'O **operador de caixa** vê apenas o PDV: ao entrar, ele é levado direto para a frente de caixa e não acessa os módulos financeiros.' },

    { h1: 'Faixas de aviso no topo' },
    { lista: [
      '**"Complete o cadastro da sua empresa para liberar todos os cálculos do Axioma."** Aparece enquanto o cadastro da empresa estiver incompleto. Clique em **Completar agora →** para ir direto à tela Empresa.',
      '**"Pedido de aval na Equipe esperando a sua decisão."** Aparece para quem pode aprovar um pedido de aval (por exemplo, a remoção de alguém de nível alto). Clique para abrir a Equipe e decidir.',
    ] },

    { h1: 'O Assistente de Ajuda' },
    { p: 'Em todas as telas internas há um botão verde-menta **Ajuda** no canto inferior esquerdo. Ele abre um chat que conhece este manual inteiro e responde perguntas como:' },
    { lista: [
      '"Onde eu cadastro um custo fixo?"',
      '"O que acontece se eu clicar em Estornar pagamento?"',
      '"Como transformo uma despesa que se repete em custo fixo?"',
      '"Para onde vai o valor que eu lanço em Receitas?"',
    ] },
    { p: 'Como funciona:' },
    { numerada: [
      'Clique em **Ajuda**. A janela abre com três sugestões de pergunta; clique numa delas ou escreva a sua no campo de baixo e aperte Enter (ou a setinha).',
      'O assistente lê o manual da tela em que você está e os manuais que combinam com a sua pergunta, e responde com o caminho exato (menu → tela → aba → botão) e o passo a passo.',
      'Abaixo da resposta aparecem botões **Abrir manual NN**: eles levam direto ao manual completo daquela tela.',
      'Para fechar, clique de novo no botão (agora com um X). A conversa fica guardada enquanto você não recarregar a página.',
    ] },
    { alerta: 'O Assistente de Ajuda **não vê os números da sua empresa**: ele recebe só a pergunta e o trecho do manual. Para entender os números (por que o lucro caiu, quanto vou pagar de imposto), use a **IA Financeira** ou a **IA Tributária**. Ele não está na frente de caixa do PDV, para não atrapalhar o operador.' },

    { h1: 'O que existe em quase todas as telas' },
    { h2: 'Cabeçalho do módulo' },
    { p: 'Cada módulo começa com um cartão azul-marinho com o nome da tela, uma frase explicando para que ela serve e os botões principais:' },
    { tabela: { colunas: ['Botão', 'O que faz', 'O que acontece depois'], larguras: [2300, 3800, 2926], linhas: [
      ['Exportar PDF', 'Gera um PDF com os dados da tela (tabelas, totais e indicadores).', 'O arquivo é baixado pelo navegador. Enquanto gera, o botão mostra "Gerando...". Nada é alterado nos dados.'],
      ['+ Novo (lançamento, cliente, conta...)', 'Abre a janela de cadastro do item principal do módulo.', 'Só grava quando você clica em Salvar. Fechar a janela (X ou Cancelar) descarta o que foi digitado.'],
      ['Tema (Escuro / Claro)', 'Troca a aparência da tela: Escuro (fundo azul-escuro) ou Claro (fundo branco e cartões creme).', 'A escolha fica guardada neste navegador. Os números não mudam.'],
    ] } },
    { h2: 'Seletor de período' },
    { p: 'Nos módulos com números ao longo do tempo há um seletor com as opções **Mês atual, Mês anterior, Trimestre atual, Ano atual, Últimos 12 meses e Personalizado**. Em Personalizado aparecem dois campos de data (início e fim). Os cards, gráficos e tabelas passam a mostrar só o período escolhido, e as setas ▲▼ comparam com o período anterior de mesmo tamanho.' },
    { h2: 'Letreiro' },
    { p: 'A faixa azul-marinho com texto passando (o letreiro) resume os números mais importantes da tela em uma linha. Passe o mouse por cima para pausar a leitura.' },
    { h2: 'Cartões' },
    { p: 'Todos os cartões têm o mesmo efeito ao passar o mouse: a borda acende e aparece uma faixa verde-menta no topo. Muitos cartões são **clicáveis**: levam ao módulo de origem daquele número ou filtram a lista da própria tela. Quando um cartão é clicável, o cursor vira uma mãozinha.' },
    { h2: 'Compartilhar (Centro de Compartilhamento)' },
    { p: 'O botão **Compartilhar** abre o Centro de Compartilhamento com estes botões:' },
    { tabela: { colunas: ['Botão', 'O que acontece'], larguras: [2600, 6426], linhas: [
      ['WhatsApp / Telegram', 'Abre o aplicativo (ou a versão web) numa nova aba com o resumo já escrito. Você escolhe o contato e envia.'],
      ['Gmail / Outlook', 'Abre um e-mail novo, já com assunto e o resumo no corpo. Você escolhe o destinatário e envia.'],
      ['E-mail', 'Abre o programa de e-mail padrão do seu computador com o resumo.'],
      ['Copiar (resumo)', 'Copia os principais números para colar onde quiser. O botão mostra "Copiado" por um instante.'],
      ['Copiar (detalhado)', 'Copia a lista completa (aparece só nas telas que têm versão detalhada).'],
      ['PDF', 'Fecha o Centro e gera o mesmo PDF do botão Exportar PDF.'],
    ] } },
    { p: 'Nada é enviado sozinho: o Axioma só prepara o texto; quem envia é você. Os valores vão sempre com centavos exatos.' },
    { h2: 'Janelas (modais)' },
    { p: 'Cadastros, detalhes e confirmações abrem em janelas sobre a tela. Toda janela fecha pelo **X** no canto ou pelo botão **Cancelar/Fechar**. Ações que apagam algo sempre pedem confirmação antes; algumas pedem também o motivo, que fica registrado no histórico.' },
    { h2: 'Ver Histórico' },
    { p: 'Em alguns módulos (como DRE e Contas a Pagar) o botão ou a aba **Histórico** mostra os fechamentos anteriores ou as alterações feitas, com quem fez e quando.' },

    { h1: 'Quem pode fazer o quê (visão geral)' },
    { tabela: { colunas: ['Nível', 'O que pode'], larguras: [2600, 6426], linhas: [
      ['Proprietário (dono)', 'Tudo, inclusive assinatura, Equipe, transferir a empresa e aprovar o que exige aval.'],
      ['CEO / Sócio / Administrador', 'Quase tudo; a remoção de pessoas de nível igual ou superior pode exigir aval de alguém acima.'],
      ['Financeiro / Contábil / Contador', 'Lançar e alterar nos módulos da sua área.'],
      ['Leitor / Consultor', 'Ver as telas, sem alterar dados (os botões de gravar ficam bloqueados).'],
      ['Operador de caixa', 'Somente o PDV (vender, abrir e fechar o caixa). Não vê custos nem módulos financeiros.'],
    ] } },
    { p: 'Os detalhes de cada tela estão na seção "Quem pode fazer o quê" do manual dela.' },

    { h1: 'Problemas comuns e soluções' },
    { tabela: { colunas: ['Problema', 'Solução'], larguras: [3400, 5626], linhas: [
      ['Os números aparecem zerados.', 'Confira o seletor de período (talvez esteja num mês sem lançamentos) e se a empresa ativa é a certa. Se a empresa acabou de ser criada, comece pelos cadastros da seção "A ordem certa para começar".'],
      ['Os impostos aparecem zerados ou estranhos.', 'Complete o regime tributário em Config → Empresa.'],
      ['Um botão está apagado (não clica).', 'Seu nível de acesso pode ser só de leitura, ou falta preencher um campo obrigatório na janela. Passe o mouse sobre o botão para ver o aviso.'],
      ['Apareceu uma mensagem de erro ao salvar.', 'A janela continua aberta com o que você digitou: nada se perde. Leia a mensagem, corrija e salve de novo. Se repetir, anote a mensagem e fale com o suporte.'],
      ['Não acho uma função.', 'Use o botão Ajuda e pergunte com as suas palavras, ou procure no Manual pelo nome do módulo.'],
      ['A tela está em outro idioma.', 'Clique em PT, EN ou ES no menu do topo.'],
      ['A tela demorou para abrir.', 'Na primeira abertura do dia o banco de dados pode levar alguns segundos para acordar. Aguarde e, se preciso, recarregue a página.'],
    ] } },

    { h1: 'Boas práticas' },
    { lista: [
      'Lance as receitas e os custos com frequência: quanto mais completos os dados, melhores as análises.',
      'Conecte o banco em **Open Finance** para trazer o extrato automaticamente.',
      'Use **Importar Documentos** para lançar notas fiscais e extratos de uma vez.',
      'Dê à sua equipe só o acesso necessário e pelo menor prazo (Manual 39 — Equipe).',
      'Na dúvida, pergunte ao **Assistente de Ajuda** antes de apagar ou alterar algo.',
    ] },
  ],
}

const en: DocumentoAxioma = {
  arquivo: '00 - Prologue, Introduction and First Steps.docx',
  titulo: 'Manual 00 — Prologue and Introduction',
  subtitulo: 'What Axioma means, what the platform is, how its intelligence engine thinks and everything that is the same on every screen',
  info: ['Axioma AI.Tech user manual  •  Version 2.0'],
  blocos: [
    { h1: 'Prologue — what "Axioma" means' },
    { h2: 'The origin of the word' },
    { p: 'The word **axiom** (axioma in Portuguese) comes from ancient Greek **ἀξίωμα (axíōma)**, meaning "that which is considered worthy", "that which recommends itself as evident". It derives from the verb **ἀξιόω (axióō)**, "to consider worthy", "to judge valid", which in turn comes from **ἄξιος (áxios)**: "having value", "in balance", "weighing the same as". It is the image of a balanced scale, where something is worth exactly what it claims to be worth.' },
    { p: 'At its origin, then, an axiom is something that **has value of its own** and **supports everything else**.' },
    { h2: 'The axiom in science' },
    { p: 'In Greek philosophy, **Aristotle** (4th century BC) used the term as a technical concept of logic: axioms are the immediate propositions one must know in order to learn anything else, the starting points of every demonstration. Shortly after, **Euclid of Alexandria**, in the *Elements* (around 300 BC), built all of geometry from a small set of axioms and postulates. From these few basic truths, by rigorous deduction, hundreds of theorems arise.' },
    { p: 'In modern mathematics and logic, from **David Hilbert** (early 20th century) onwards, the axiom came to be understood as the **fundamental premise of a formal system**: a clear, explicit starting rule from which everything else is derived in a verifiable way. Arithmetic, set theory and computer science itself rest on axiomatic systems: a few solid foundations, rigorous reasoning and conclusions anyone can check.' },
    { nota: '**In short:** an axiom is a reliable starting point. When the foundations are solid and the reasoning is rigorous, so are the conclusions.' },
    { h2: 'Why the platform is called Axioma' },
    { p: 'A company also needs axioms: **true figures** about what comes in, what goes out, what is owed and what is receivable. Without them, every decision is a guess. Axioma was built on this idea:' },
    { lista: [
      '**The figures are the foundation, and they are real.** Every calculation starts from the company\'s own entries, documents and statements. No fictitious data is mixed with yours.',
      '**The reasoning is rigorous and verifiable.** Taxes, totals, projections and indicators are calculated by fixed, auditable rules, not by guesswork.',
      '**Intelligence interprets, never invents.** Artificial intelligence explains the figures and suggests paths, and every value it cites is checked against the company\'s data.',
      '**Your data is yours.** The privacy and security of company and personal information come before any feature.',
    ] },
    { p: 'Just as Euclid started from a few truths to build all of geometry, Axioma starts from your company\'s real figures to build a complete view of the business.' },

    { h1: 'Introduction — the platform' },
    { p: '**Axioma AI.Tech** is a **digital CFO**: a financial, accounting and business intelligence platform that brings together in one place everything a finance director and an accountant follow (revenues, costs, cash, results, debts, taxes, accounting entries, customers, suppliers, inventory, goals, investments and the economic scenario) and turns this data into decisions.' },
    { p: 'It was designed for the reality of Brazilian companies, from the individual micro-entrepreneur (MEI) to mid-sized companies, and works in Portuguese, English and Spanish.' },
    { h2: 'Our goal' },
    { p: 'Most small and medium-sized companies have no access to a finance director. Important decisions, such as how much to charge, when to hire, whether a loan fits or how to legally pay less tax, end up being made in the dark. Axioma\'s goal is to **put the intelligence of an experienced CFO within reach of any company**, available at any time, with the business\'s real figures, in plain language and with full respect for the privacy of its users.' },
    { p: 'Every Axioma screen follows the same principle: show **what is happening, why it is happening and what the next step is**.' },

    { h1: 'Innovation: the best of world technology, designed for Brazil' },
    { p: 'Axioma closely follows the most advanced developments in financial management and artificial intelligence in the world\'s major technology hubs and brings these ideas to the reality of Brazilian companies, with our laws, our taxes and our banking system.' },
    { tabela: { colunas: ['Reference', 'What it inspires', 'How it appears in Axioma'], larguras: [1900, 3300, 3826], linhas: [
      ['China', 'Platforms that integrate sales, instant payments and management in one place, and intensive use of real-time data.', 'POS integrated with inventory and finance; bill payment via Pix inside the platform (in preparation); dashboards updated with the day\'s data.'],
      ['Europe', 'Open Banking (with the PSD2 directive) and privacy by design (inspired by the GDPR).', 'Bank connection via Open Finance with the holder\'s consent; data isolation per company; AI usage auditing without storing content; retention and trash rules for personal data.'],
      ['United States', 'State-of-the-art language models and AI-powered financial planning tools (FP&A).', 'Layered AI orchestration engine, with specialists by area and sector, automatic checking of figures, executive analyses and José\'s long-term plans.'],
    ] } },
    { h2: 'Features that take management beyond the conventional' },
    { lista: [
      '**Automatic checking of AI figures:** every value cited by the intelligence is checked against the company\'s real data before it reaches you.',
      '**Nexus and José:** a daily reading of the Brazilian and world economy from official public sources (such as the Central Bank of Brazil, IBGE, World Bank and OECD), crossed with your company\'s sector, with a scoreboard comparing what was forecast with what actually happened.',
      '**Cash digital twin:** a simulation of the company\'s cash to test decisions before making them (Treasury).',
      '**Smart invoice reading:** XML, PDF or photo become entries distributed to the right modules, always with human review before saving.',
      '**Team with hierarchy and time limits:** invitations tied to an e-mail, confirmation codes, temporary access and an accountability trail.',
      '**Help Assistant:** a chat on every screen that explains where each feature is and what each button does.',
      '**Everything in three languages:** Portuguese, English and Spanish on every screen, in the manuals, the Terms and the Privacy Policy.',
    ] },
    { p: 'Our commitment is to keep researching and adopting innovations whenever they bring real gains to the company, without compromising the security and privacy of users.' },

    { h1: 'Axioma\'s intelligence engine' },
    { p: 'The heart of the platform is an **artificial intelligence orchestration engine**: a single "brain", used by every screen, built in layers to answer like a real finance director, safely and with controlled cost.' },
    { tabela: { colunas: ['Layer', 'What it does', 'Uses AI?'], larguras: [2200, 5326, 1500], linhas: [
      ['0. Company snapshot', 'Gathers the figures from all modules: revenue, costs by name, taxes by regime, profit, margin, break-even point, cash, debts, receivables and payables, delinquency, inventory and tax obligations. Identifies the company\'s sector (the full CNAE classification) and generates situation alerts.', 'No'],
      ['1. Triage', 'Classifies the question as routine (a direct fact), analysis (needs reasoning) or strategy (long-term decision). First by fixed rules; only when in doubt, by a fast AI.', 'Sometimes'],
      ['2. Executor', 'Sends the question to the AI model suited to its complexity: routine uses fast models; analyses and strategies use the most advanced models. If the question turns out harder than it seemed, it moves up a level automatically.', 'Yes'],
      ['3. Data lookup', 'When it needs detail (for example, the bills due this week or the largest debtors), the AI queries the company\'s data in read-only mode. It never changes anything.', 'Yes'],
      ['4. Checking', 'Every amount in reais cited in the answer is checked against real data. Anything that cannot be checked is flagged on screen.', 'No'],
    ] } },
    { h2: 'Specialists by area and sector' },
    { p: 'For each question, the engine picks up to three **specialist manuals** (cash, costs, pricing, debt, tax, collections, inventory, growth, sales and economy) and the company\'s **sector manual**, among 40 sectors covering the full CNAE classification. A bakery and a trucking company receive different guidance, because what weighs on each one\'s cash is different.' },
    { h2: 'The assistants you will find' },
    { tabela: { colunas: ['Where', 'What it does'], larguras: [2600, 6426], linhas: [
      ['Help Assistant (Help button, bottom-left corner)', 'Explains how to use Axioma: where each feature is, what each button does, where it leads and the step-by-step. It does not see the company\'s figures.'],
      ['Financial AI', 'Talks about the company\'s financial health: score, anomalies, projections and action plans (Manual 36).'],
      ['Tax AI', 'Compares tax regimes and explains the tax burden and the Tax Reform with your figures (Manual 37).'],
      ['José (Nexus)', 'Follows the Brazilian and world economy, explains how each event affects your industry and builds 1- to 10-year plans (Manual 43).'],
      ['AI MEI Advisor', 'Answers MEI questions about DAS, revenue cap, income tax and pricing (Manual 08).'],
      ['Analyses in the modules', 'The "Ask Axioma CFO" blocks and the analysis buttons in several modules generate an executive analysis of that screen.'],
      ['Invoice reading', 'Reads invoices in PDF or photo, distributes the items to the right modules and asks review questions before saving (Manual 33).'],
    ] } },
    { h2: 'The engine\'s commitments to you' },
    { lista: [
      '**Never invent a figure:** the math is done by Axioma; the AI interprets.',
      '**Privacy first:** the AI receives only what it needs to answer; contracted providers do not use your data to train models; the audit log records usage, never the content of conversations.',
      '**You decide:** the AI guides and suggests; no decision is made by it on your behalf, and it never saves, deletes or pays anything on its own.',
      '**Usage transparency:** the Settings → AI Usage screen shows how many questions were asked, how many figures were checked and the cost.',
      '**Always working:** if the AI is unavailable, screens keep answering with rule-based analyses.',
    ] },

    { h1: 'How to use this manual' },
    { p: 'The manual is divided into numbered documents, one per module, in the same order as the Axioma menu. This first one introduces the platform and explains what is the same on every screen. The following ones explain each module in detail, always in the same order of sections, so you can find the answer quickly:' },
    { tabela: { colunas: ['Section', 'What it answers'], larguras: [2800, 6226], linhas: [
      ['What it is for', 'The problem the screen solves and when to use it.'],
      ['How to get there', 'The menu path and the shortcuts from other screens that lead to it.'],
      ['Before you start', 'What must be registered for the screen to show correct figures.'],
      ['Screen map', 'What appears from top to bottom: cards, tabs, charts and lists.'],
      ['Buttons and actions', 'Each button: what it does, where it leads and what happens next (whether it saves, deletes, or can be undone).'],
      ['Step by step', 'The most common tasks, numbered.'],
      ['Links with other modules', 'Where the figures come from and where they go.'],
      ['Who can do what', 'What each access level can see or change.'],
      ['Common problems and solutions', 'The most frequent questions and errors, with the solution.'],
    ] } },
    { p: 'The same manual is available inside Axioma, in the **Manual** button on the top menu, and as PDFs in three languages. If you prefer to ask, use the **Help Assistant** (section below).' },

    { h1: 'First steps' },
    { h2: 'Create your account and sign in' },
    { numerada: [
      'Go to **axiomaai.com.br**. On the sign-in screen, click **Sign up** (or **Sign up with Google**, to use your Google account).',
      'Enter your name, e-mail and a password. Complete the anti-bot check (the Cloudflare box) when it appears.',
      'Confirm your e-mail through the link or code sent to your inbox.',
      'Choose a plan on the **Plans** screen to unlock the modules (Manual 40).',
      'On first sign-in, Axioma automatically creates your company named "Minha Empresa" (My Company). Complete its profile in **Settings → Company** (the mint-green bar at the top of the screen reminds you and takes you there with one click).',
    ] },
    { nota: 'Forgot your password? On the sign-in screen click **Forgot password?**. You will receive an e-mail with a link to create a new one.' },
    { h2: 'Joining by invitation' },
    { numerada: [
      'Open the invitation link you received by e-mail.',
      'Fill in your name (and CPF — Brazilian taxpayer ID — when access is longer than 30 days or has no end date). Check who invited you.',
      'Read and accept the Terms of Use and the Privacy Policy (LGPD).',
      'Click **Get code by e-mail** and type the numeric code you received. It proves the e-mail is yours.',
      'Done: you go straight into the company that invited you, with the access level chosen by the inviter. In some cases access still needs to be approved by the owner or an administrator; the screen tells you.',
    ] },
    { h2: 'The right order to start' },
    { p: 'For Axioma to show correct figures from day one, follow this order:' },
    { numerada: [
      '**Settings → Company:** CNPJ, tax regime (Simples, Presumido, Real or MEI) and activity (CNAE). Without the regime, taxes cannot be calculated.',
      '**Financial → Fixed Costs:** rent, salaries, software, accountant and everything that repeats every month.',
      '**Financial → Revenue:** sales and income (or connect your bank in **Open Finance**, or use **Import Documents**).',
      '**Commercial → Clients and Suppliers:** who buys from you and who you buy from.',
      '**Commercial → Accounts Payable and Receivables:** what is due in the coming days.',
      'Go back to the **Dashboard**: the figures already appear cross-referenced.',
    ] },

    { h1: 'The top menu' },
    { p: 'The menu is fixed at the top of every screen, like a board of cards in two rows. The card of the section you are in lights up in mint green. Click a group (those with the ▼ arrow) to open its list of screens:' },
    { tabela: { colunas: ['Card', 'What it contains'], larguras: [2400, 6626], linhas: [
      ['Dashboard', 'Company overview (Manual 01).'],
      ['Nexus', 'Market intelligence with the assistant José (Manual 43).'],
      ['Financial ▼', 'Revenue, Fixed Costs, Variable Costs, Cash Flow, Income Statement, Debt, Treasury (Manuals 10 to 16).'],
      ['Accounting ▼', 'Accountant, Tax, General Ledger, Trial Balance, Accounting Income Statement (Manuals 17 to 21).'],
      ['Commercial ▼', 'Clients, Suppliers, Accounts Payable, Inventory, Receivables, Default (Manuals 26 to 31).'],
      ['Growth ▼', 'Goals, Investments, Simulations, Pricing (Manuals 22 to 25).'],
      ['Management ▼', 'Cost Centers, Import Documents, Reports, Open Finance (Manuals 32 to 35).'],
      ['Team', 'Company people, invitations and access levels (Manual 39).'],
      ['PT / EN / ES', 'Changes the language of all of Axioma: Portuguese, English or Spanish.'],
      ['MEI ▼ (PRO)', 'MEI Dashboard, Cockpit, Revenue, DAS & Obligations, Tax Reform, MEI Pricing, AI MEI Advisor, Income Tax (Manuals 02 to 09).'],
      ['PDV (PRO)', 'Point of sale, products, back office and NF-e entry (Manual 42).'],
      ['AI Premium ▼', 'Financial AI and Tax AI (Manuals 36 and 37).'],
      ['Settings ▼', 'Company, Plans, AI Usage and, for the owner, Team (Manuals 38 to 41).'],
      ['Manual', 'This manual, inside Axioma, in three languages.'],
      ['Terms of Use / Privacy', 'The legal documents, with language switching.'],
      ['BANK', 'Shortcut to connect your bank (Open Finance, Manual 35).'],
      ['Logout', 'Ends your session securely.'],
    ] } },
    { p: 'On mobile, the menu becomes the **☰** button in the top corner, with the same items in a list.' },
    { nota: 'The **cashier** sees only the POS: on sign-in they are taken straight to the point of sale and cannot access the financial modules.' },

    { h1: 'Notice bars at the top' },
    { lista: [
      '**"Complete your company profile to unlock all of Axioma\'s calculations."** Appears while the company profile is incomplete. Click **Complete now →** to go straight to the Company screen.',
      '**"Approval request in the Team awaiting your decision."** Appears for those who can approve a request (for example, removing someone of a high level). Click to open the Team and decide.',
    ] },

    { h1: 'The Help Assistant' },
    { p: 'On every internal screen there is a mint-green **Help** button in the bottom-left corner. It opens a chat that knows this entire manual and answers questions such as:' },
    { lista: [
      '"Where do I register a fixed cost?"',
      '"What happens if I click Reverse payment?"',
      '"How do I turn a recurring expense into a fixed cost?"',
      '"Where does the amount I enter in Revenue go?"',
    ] },
    { p: 'How it works:' },
    { numerada: [
      'Click **Help**. The window opens with three suggested questions; click one or type yours in the field at the bottom and press Enter (or the arrow).',
      'The assistant reads the manual of the screen you are on and the manuals that match your question, and answers with the exact path (menu → screen → tab → button) and the step-by-step.',
      'Below the answer, **Open manual NN** buttons appear: they take you straight to the full manual of that screen.',
      'To close, click the button again (now with an X). The conversation is kept until you reload the page.',
    ] },
    { alerta: 'The Help Assistant **does not see your company\'s figures**: it receives only the question and the manual excerpt. To understand the figures (why profit fell, how much tax I will pay), use **Financial AI** or **Tax AI**. It is not shown on the POS checkout screen, so it does not get in the cashier\'s way.' },

    { h1: 'What exists on almost every screen' },
    { h2: 'Module header' },
    { p: 'Each module starts with a navy-blue card with the screen name, a sentence explaining what it is for and the main buttons:' },
    { tabela: { colunas: ['Button', 'What it does', 'What happens next'], larguras: [2300, 3800, 2926], linhas: [
      ['Export PDF', 'Generates a PDF with the screen\'s data (tables, totals and indicators).', 'The file is downloaded by the browser. While generating, the button shows "Gerando..." (Generating). No data is changed.'],
      ['+ New (entry, client, bill...)', 'Opens the registration window for the module\'s main item.', 'It only saves when you click Save. Closing the window (X or Cancel) discards what was typed.'],
      ['Theme (Dark / Light)', 'Changes the look of the screen: Dark (dark blue background) or Light (white background and cream cards).', 'The choice is kept in this browser. Figures do not change.'],
    ] } },
    { h2: 'Period selector' },
    { p: 'In modules with figures over time there is a selector with the options **Current month, Previous month, Current quarter, Current year, Last 12 months and Custom**. In Custom, two date fields appear (start and end). Cards, charts and tables show only the chosen period, and the ▲▼ arrows compare with the previous period of the same length.' },
    { h2: 'Ticker' },
    { p: 'The navy-blue band with scrolling text (the ticker) summarizes the screen\'s most important figures in one line. Hover over it to pause.' },
    { h2: 'Cards' },
    { p: 'All cards have the same hover effect: the border lights up and a mint-green bar appears at the top. Many cards are **clickable**: they lead to the module where that figure comes from or filter the list on the same screen. When a card is clickable, the cursor turns into a hand.' },
    { h2: 'Share (Sharing Center)' },
    { p: 'The **Share** button opens the Sharing Center with these buttons:' },
    { tabela: { colunas: ['Button', 'What happens'], larguras: [2600, 6426], linhas: [
      ['WhatsApp / Telegram', 'Opens the app (or web version) in a new tab with the summary already written. You choose the contact and send.'],
      ['Gmail / Outlook', 'Opens a new e-mail with subject and summary in the body. You choose the recipient and send.'],
      ['E-mail', 'Opens your computer\'s default e-mail program with the summary.'],
      ['Copy (summary)', 'Copies the main figures to paste wherever you want. The button shows "Copied" for a moment.'],
      ['Copy (detailed)', 'Copies the full list (only on screens that have a detailed version).'],
      ['PDF', 'Closes the Center and generates the same PDF as the Export PDF button.'],
    ] } },
    { p: 'Nothing is sent automatically: Axioma only prepares the text; you are the one who sends it. Amounts always go with exact cents.' },
    { h2: 'Windows (modals)' },
    { p: 'Forms, details and confirmations open in windows over the screen. Every window closes with the **X** in the corner or the **Cancel/Close** button. Actions that delete something always ask for confirmation first; some also ask for the reason, which is recorded in the history.' },
    { h2: 'View History' },
    { p: 'In some modules (such as Income Statement and Accounts Payable) the **History** button or tab shows previous closings or the changes made, with who made them and when.' },

    { h1: 'Who can do what (overview)' },
    { tabela: { colunas: ['Level', 'What they can do'], larguras: [2600, 6426], linhas: [
      ['Owner', 'Everything, including subscription, Team, transferring the company and approving what requires sign-off.'],
      ['CEO / Partner / Administrator', 'Almost everything; removing people of an equal or higher level may require sign-off from someone above.'],
      ['Finance / Bookkeeping / Accountant', 'Enter and change data in the modules of their area.'],
      ['Read-only / Consultant', 'View screens, without changing data (save buttons are blocked).'],
      ['Cashier', 'Only the POS (sell, open and close the register). Does not see costs or financial modules.'],
    ] } },
    { p: 'The details of each screen are in the "Who can do what" section of its manual.' },

    { h1: 'Common problems and solutions' },
    { tabela: { colunas: ['Problem', 'Solution'], larguras: [3400, 5626], linhas: [
      ['Figures show as zero.', 'Check the period selector (it may be on a month with no entries) and whether the active company is the right one. If the company was just created, start with the registrations in "The right order to start".'],
      ['Taxes show as zero or look odd.', 'Complete the tax regime in Settings → Company.'],
      ['A button is greyed out (does not click).', 'Your access level may be read-only, or a required field in the window is missing. Hover over the button to see the notice.'],
      ['An error message appeared when saving.', 'The window stays open with what you typed: nothing is lost. Read the message, fix it and save again. If it repeats, note the message and contact support.'],
      ['I can\'t find a feature.', 'Use the Help button and ask in your own words, or look in the Manual by the module name.'],
      ['The screen is in another language.', 'Click PT, EN or ES on the top menu.'],
      ['The screen took a while to open.', 'On the first opening of the day the database may take a few seconds to wake up. Wait and, if needed, reload the page.'],
    ] } },

    { h1: 'Good practices' },
    { lista: [
      'Enter revenues and costs frequently: the more complete the data, the better the analyses.',
      'Connect your bank in **Open Finance** to bring in the statement automatically.',
      'Use **Import Documents** to enter invoices and statements all at once.',
      'Give your team only the access they need and for the shortest time (Manual 39 — Team).',
      'When in doubt, ask the **Help Assistant** before deleting or changing something.',
    ] },
  ],
}

const es: DocumentoAxioma = {
  arquivo: '00 - Prólogo, Presentación y Primeros Pasos.docx',
  titulo: 'Manual 00 — Prólogo y Presentación',
  subtitulo: 'Qué significa Axioma, qué es la plataforma, cómo piensa su motor de inteligencia y todo lo que es igual en todas las pantallas',
  info: ['Manual de uso de Axioma AI.Tech  •  Versión 2.0'],
  blocos: [
    { h1: 'Prólogo — qué significa "Axioma"' },
    { h2: 'El origen de la palabra' },
    { p: 'La palabra **axioma** viene del griego antiguo **ἀξίωμα (axíōma)**, que significa "lo que se considera digno", "lo que se recomienda por sí mismo como evidente". Deriva del verbo **ἀξιόω (axióō)**, "considerar digno", "juzgar válido", que a su vez nace de **ἄξιος (áxios)**: "que tiene valor", "que está en equilibrio", "que pesa lo mismo que". Es la imagen de una balanza en equilibrio, en la que algo vale exactamente lo que dice valer.' },
    { p: 'En su origen, por lo tanto, axioma es aquello que **tiene valor propio** y **sostiene todo lo demás**.' },
    { h2: 'El axioma en la ciencia' },
    { p: 'En la filosofía griega, **Aristóteles** (siglo IV a.C.) usó el término como concepto técnico de la lógica: los axiomas son las proposiciones inmediatas que hay que conocer para aprender cualquier otra cosa, los puntos de partida de toda demostración. Poco después, **Euclides de Alejandría**, en los *Elementos* (cerca del 300 a.C.), construyó toda la geometría a partir de un pequeño conjunto de axiomas y postulados. De esas pocas verdades de base, por deducción rigurosa, nacen cientos de teoremas.' },
    { p: 'En la matemática y la lógica modernas, a partir de **David Hilbert** (inicios del siglo XX), el axioma pasó a entenderse como la **premisa fundamental de un sistema formal**: una regla de partida, clara y explícita, de la que todo lo demás se deriva de forma verificable. La aritmética, la teoría de conjuntos y la propia ciencia de la computación se apoyan en sistemas axiomáticos: pocas bases sólidas, razonamiento riguroso y conclusiones que cualquier persona puede verificar.' },
    { nota: '**En resumen:** un axioma es un punto de partida confiable. Cuando las bases son sólidas y el razonamiento es riguroso, las conclusiones también lo son.' },
    { h2: 'Por qué la plataforma se llama Axioma' },
    { p: 'Una empresa también necesita axiomas: **números verdaderos** sobre lo que entra, lo que sale, lo que se debe y lo que se tiene por cobrar. Sin ellos, toda decisión es una conjetura. Axioma fue construido sobre esta idea:' },
    { lista: [
      '**Los números son la base, y son reales.** Cada cálculo parte de los registros, documentos y extractos de la propia empresa. Ningún dato ficticio se mezcla con los suyos.',
      '**El razonamiento es riguroso y verificable.** Impuestos, totales, proyecciones e indicadores se calculan con reglas fijas y auditables, no por adivinación.',
      '**La inteligencia interpreta, nunca inventa.** La inteligencia artificial explica los números y sugiere caminos, y cada valor que cita se verifica contra los datos de la empresa.',
      '**Sus datos son suyos.** La privacidad y la seguridad de la información de la empresa y de las personas vienen antes que cualquier funcionalidad.',
    ] },
    { p: 'Así como Euclides partió de pocas verdades para construir toda la geometría, Axioma parte de los números reales de su empresa para construir la visión completa del negocio.' },

    { h1: 'Presentación — la plataforma' },
    { p: '**Axioma AI.Tech** es un **CFO digital**: una plataforma de gestión financiera, contable y de inteligencia empresarial que reúne en un solo lugar todo lo que un director financiero y un contador siguen (ingresos, costos, caja, resultado, deudas, impuestos, asientos contables, clientes, proveedores, inventario, metas, inversiones y el escenario económico) y transforma esos datos en decisiones.' },
    { p: 'Fue pensado para la realidad de las empresas brasileñas, desde el Microemprendedor Individual (MEI) hasta la empresa mediana, y funciona en portugués, inglés y español.' },
    { h2: 'Nuestro objetivo' },
    { p: 'La mayoría de las pequeñas y medianas empresas no tiene acceso a un director financiero. Decisiones importantes, como cuánto cobrar, cuándo contratar, si cabe un préstamo o cómo pagar menos impuestos dentro de la ley, terminan tomándose a ciegas. El objetivo de Axioma es **poner la inteligencia de un CFO experimentado al alcance de cualquier empresa**, disponible a cualquier hora, con los números reales del negocio, en lenguaje sencillo y con total respeto a la privacidad de quien lo usa.' },
    { p: 'Cada pantalla de Axioma sigue el mismo principio: mostrar **qué está pasando, por qué está pasando y cuál es el próximo paso**.' },

    { h1: 'Innovación: lo mejor de la tecnología mundial, pensado para Brasil' },
    { p: 'Axioma sigue de cerca lo más avanzado en gestión financiera e inteligencia artificial en los grandes polos tecnológicos del mundo y trae esas ideas a la realidad de la empresa brasileña, con nuestras leyes, nuestros impuestos y nuestro sistema bancario.' },
    { tabela: { colunas: ['Referencia', 'Qué inspira', 'Cómo aparece en Axioma'], larguras: [1900, 3300, 3826], linhas: [
      ['China', 'Plataformas que integran ventas, pagos instantáneos y gestión en el mismo lugar, y el uso intensivo de datos en tiempo real.', 'PDV integrado al inventario y a las finanzas; pago de cuentas por Pix dentro de la plataforma (en preparación); paneles que se actualizan con los datos del día.'],
      ['Europa', 'Open Banking (con la directiva PSD2) y privacidad desde el diseño (privacy by design, inspirada en el GDPR).', 'Conexión bancaria por Open Finance con consentimiento del titular; aislamiento de los datos por empresa; auditoría del uso de IA sin guardar contenido; reglas de plazo y papelera para datos personales.'],
      ['Estados Unidos', 'Modelos de lenguaje de última generación y herramientas de planificación financiera con IA (FP&A).', 'Motor de orquestación de IA en capas, con especialistas por área y por sector, verificación automática de números, análisis ejecutivos y planes de largo plazo de José.'],
    ] } },
    { h2: 'Funciones que llevan la gestión más allá de lo convencional' },
    { lista: [
      '**Verificación automática de números de la IA:** cada valor citado por la inteligencia se verifica contra los datos reales de la empresa antes de llegar a usted.',
      '**Nexus y José:** lectura diaria de la economía de Brasil y del mundo a partir de fuentes públicas oficiales (como el Banco Central de Brasil, IBGE, Banco Mundial y OCDE), cruzada con el sector de su empresa, con un marcador que compara lo previsto con lo que de hecho ocurrió.',
      '**Gemelo digital de la caja:** simulación de la caja de la empresa para probar decisiones antes de tomarlas (Tesorería).',
      '**Lectura inteligente de facturas:** XML, PDF o foto se convierten en registros distribuidos en los módulos correctos, siempre con revisión humana antes de guardar.',
      '**Equipo con jerarquía y plazos:** invitaciones vinculadas a un e-mail, códigos de confirmación, acceso temporal y rastro de responsabilidad.',
      '**Asistente de Ayuda:** un chat en todas las pantallas que explica dónde está cada función y qué hace cada botón.',
      '**Todo en tres idiomas:** portugués, inglés y español en todas las pantallas, en los manuales, los Términos y la Política de Privacidad.',
    ] },
    { p: 'Nuestro compromiso es seguir investigando e incorporando innovaciones siempre que traigan una ganancia real para la empresa, sin renunciar a la seguridad y la privacidad de quien lo usa.' },

    { h1: 'El motor de inteligencia de Axioma' },
    { p: 'El corazón de la plataforma es un **motor de orquestación de inteligencia artificial**: un "cerebro" único, usado por todas las pantallas, construido en capas para responder como un director financiero de verdad, con seguridad y con costo controlado.' },
    { tabela: { colunas: ['Capa', 'Qué hace', '¿Usa IA?'], larguras: [2200, 5326, 1500], linhas: [
      ['0. Retrato de la empresa', 'Reúne los números de todos los módulos: ingresos, costos por nombre, impuestos por régimen, utilidad, margen, punto de equilibrio, caja, deudas, cuentas por cobrar y por pagar, morosidad, inventario y obligaciones fiscales. Identifica el sector de la empresa (toda la clasificación CNAE) y genera las alertas de la situación.', 'No'],
      ['1. Clasificación', 'Clasifica la pregunta como rutina (un dato directo), análisis (necesita razonamiento) o estrategia (decisión de largo plazo). Primero con reglas fijas; solo en caso de duda, con una IA rápida.', 'A veces'],
      ['2. Ejecutor', 'Lleva la pregunta al modelo de IA adecuado a su complejidad: la rutina usa modelos rápidos; los análisis y estrategias usan los modelos más avanzados. Si la pregunta resulta más difícil de lo que parecía, sube de nivel automáticamente.', 'Sí'],
      ['3. Consulta de datos', 'Cuando necesita detalle (por ejemplo, las cuentas que vencen esta semana o los mayores deudores), la IA consulta los datos de la empresa en modo de solo lectura. Nunca altera nada.', 'Sí'],
      ['4. Verificación', 'Todo valor en reales citado en la respuesta se verifica contra los datos reales. Lo que no pueda verificarse se señala en la pantalla.', 'No'],
    ] } },
    { h2: 'Especialistas por área y por sector' },
    { p: 'Para cada pregunta, el motor elige hasta tres **manuales especialistas** (caja, costos, precios, deuda, tributario, cobranza, inventario, crecimiento, ventas y economía) y el **manual del sector** de la empresa, entre 40 sectores que cubren toda la clasificación CNAE. Una panadería y una transportadora reciben orientaciones diferentes, porque lo que pesa en la caja de cada una es diferente.' },
    { h2: 'Los asistentes que encontrará' },
    { tabela: { colunas: ['Dónde', 'Qué hace'], larguras: [2600, 6426], linhas: [
      ['Asistente de Ayuda (botón Ayuda, esquina inferior izquierda)', 'Explica cómo usar Axioma: dónde está cada función, qué hace cada botón, a dónde lleva y el paso a paso. No ve los números de la empresa.'],
      ['IA Financiera', 'Conversa sobre la salud financiera de la empresa: puntuación, anomalías, proyecciones y planes de acción (Manual 36).'],
      ['IA Tributaria', 'Compara regímenes tributarios y explica la carga de impuestos y la Reforma Tributaria con sus números (Manual 37).'],
      ['José (Nexus)', 'Sigue la economía de Brasil y del mundo, explica cómo cada acontecimiento afecta a su rubro y arma planes de 1 a 10 años (Manual 43).'],
      ['IA Advisor MEI', 'Responde dudas del MEI sobre DAS, tope de facturación, impuesto a la renta y precio (Manual 08).'],
      ['Análisis en los módulos', 'Los bloques "Pregunte al Axioma CFO" y los botones de análisis presentes en varios módulos generan un análisis ejecutivo de esa pantalla.'],
      ['Lectura de facturas', 'Lee facturas en PDF o foto, distribuye los ítems en los módulos correctos y hace preguntas de verificación antes de guardar (Manual 33).'],
    ] } },
    { h2: 'Compromisos del motor con usted' },
    { lista: [
      '**Nunca inventar números:** las cuentas las hace Axioma; la IA interpreta.',
      '**La privacidad primero:** la IA recibe solo lo necesario para responder; los proveedores contratados no usan sus datos para entrenar modelos; el registro de auditoría guarda el uso, nunca el contenido de las conversaciones.',
      '**Usted decide:** la IA orienta y sugiere; ninguna decisión se toma en su nombre, y nunca guarda, elimina ni paga nada por sí sola.',
      '**Transparencia de consumo:** la pantalla Config → Uso de la IA muestra cuántas preguntas se hicieron, cuántos números se verificaron y el costo.',
      '**Siempre funcionar:** si la IA no está disponible, las pantallas siguen respondiendo con análisis por reglas.',
    ] },

    { h1: 'Cómo usar este manual' },
    { p: 'El manual está dividido en documentos numerados, uno por módulo, en el mismo orden del menú de Axioma. Este primero presenta la plataforma y explica lo que es igual en todas las pantallas. Los siguientes explican cada módulo en detalle, siempre con el mismo orden de secciones, para que encuentre la respuesta rápido:' },
    { tabela: { colunas: ['Sección', 'Qué responde'], larguras: [2800, 6226], linhas: [
      ['Para qué sirve', 'El problema que resuelve la pantalla y cuándo usarla.'],
      ['Cómo llegar', 'El camino en el menú y los atajos de otras pantallas que llevan a ella.'],
      ['Antes de empezar', 'Lo que debe estar registrado para que la pantalla muestre números correctos.'],
      ['Mapa de la pantalla', 'Lo que aparece de arriba abajo: tarjetas, pestañas, gráficos y listas.'],
      ['Botones y acciones', 'Cada botón: qué hace, a dónde lleva y qué pasa después (si guarda, si elimina, si se puede deshacer).'],
      ['Paso a paso', 'Las tareas más comunes, numeradas.'],
      ['Conexiones con otros módulos', 'De dónde vienen los números y a dónde van.'],
      ['Quién puede hacer qué', 'Lo que cada nivel de acceso puede ver o modificar.'],
      ['Problemas comunes y soluciones', 'Las dudas y los errores más frecuentes, con la solución.'],
    ] } },
    { p: 'El mismo manual está dentro de Axioma, en el botón **Manual** del menú superior, y en PDF en los tres idiomas. Si prefiere preguntar, use el **Asistente de Ayuda** (sección más abajo).' },

    { h1: 'Primeros pasos' },
    { h2: 'Crear la cuenta e ingresar' },
    { numerada: [
      'Acceda a **axiomaai.com.br**. En la pantalla de ingreso, haga clic en **Registrarse** (o en **Registrar con Google**, para usar su cuenta de Google).',
      'Informe nombre, e-mail y una contraseña. Complete la verificación anti-robot (la casilla de Cloudflare) cuando aparezca.',
      'Confirme el e-mail con el enlace o código enviado a su bandeja de entrada.',
      'Elija un plan en la pantalla **Planes** para habilitar los módulos (Manual 40).',
      'En el primer ingreso, Axioma crea automáticamente su empresa con el nombre "Minha Empresa" (Mi Empresa). Complete el registro en **Config → Empresa** (la franja verde menta en la parte superior de la pantalla se lo recuerda y lo lleva allí con un clic).',
    ] },
    { nota: '¿Olvidó la contraseña? En la pantalla de ingreso haga clic en **¿Olvidó su contraseña?**. Recibirá un e-mail con un enlace para crear una nueva.' },
    { h2: 'Ingresar por invitación' },
    { numerada: [
      'Abra el enlace de la invitación que llegó a su e-mail.',
      'Complete el nombre (y el CPF — número de contribuyente brasileño — cuando el acceso sea de más de 30 días o sin plazo). Verifique quién lo invitó.',
      'Lea y acepte los Términos de Uso y la Política de Privacidad (LGPD).',
      'Haga clic en **Recibir código por correo** y escriba el código numérico que llegó. Prueba que el e-mail es suyo.',
      'Listo: entra directamente a la empresa que lo invitó, con el nivel de acceso elegido por quien invitó. En algunos casos el acceso todavía debe ser aprobado por el dueño o el administrador; la pantalla lo avisa.',
    ] },
    { h2: 'El orden correcto para empezar' },
    { p: 'Para que Axioma muestre números correctos desde el primer día, siga este orden:' },
    { numerada: [
      '**Config → Empresa:** CNPJ, régimen tributario (Simples, Presumido, Real o MEI) y actividad (CNAE). Sin el régimen, los impuestos no pueden calcularse.',
      '**Financiero → Costos Fijos:** alquiler, salarios, sistemas, contador y todo lo que se repite cada mes.',
      '**Financiero → Ingresos:** las ventas y entradas (o conecte el banco en **Open Finance**, o use **Importar Documentos**).',
      '**Comercial → Clientes y Proveedores:** quién le compra y a quién le compra.',
      '**Comercial → Cuentas por Pagar y Cuentas por Cobrar:** lo que vence en los próximos días.',
      'Vuelva al **Dashboard**: los números ya aparecen cruzados.',
    ] },

    { h1: 'El menú superior' },
    { p: 'El menú está fijo en la parte superior de todas las pantallas, como un tablero de tarjetas en dos filas. La tarjeta de la sección en la que usted está se enciende en verde menta. Haga clic en un grupo (los que tienen la flecha ▼) para abrir su lista de pantallas:' },
    { tabela: { colunas: ['Tarjeta', 'Qué contiene'], larguras: [2400, 6626], linhas: [
      ['Panel (Dashboard)', 'Visión general de la empresa (Manual 01).'],
      ['Nexus', 'Inteligencia de mercado con el asistente José (Manual 43).'],
      ['Financiero ▼', 'Ingresos, Costos Fijos, Costos Variables, Flujo de Caja, Estado de Resultados, Endeudamiento, Tesorería (Manuales 10 a 16).'],
      ['Contabilidad ▼', 'Contador, Fiscal, Libro Mayor, Balance de Comprobación, Estado de Resultados Contable (Manuales 17 a 21).'],
      ['Comercial ▼', 'Clientes, Proveedores, Cuentas por Pagar, Inventario, Cuentas por Cobrar, Morosidad (Manuales 26 a 31).'],
      ['Crecimiento ▼', 'Metas, Inversiones, Simulaciones, Precios (Manuales 22 a 25).'],
      ['Gestión ▼', 'Centros de Costo, Importar Documentos, Informes, Open Finance (Manuales 32 a 35).'],
      ['Equipo', 'Personas de la empresa, invitaciones y niveles de acceso (Manual 39).'],
      ['PT / EN / ES', 'Cambia el idioma de todo Axioma: portugués, inglés o español.'],
      ['MEI ▼ (PRO)', 'Panel MEI, Cockpit, Facturación, DAS & Obligaciones, Reforma Tributaria, Precios MEI, IA Advisor MEI, Impuesto a la Renta (Manuales 02 a 09).'],
      ['PDV (PRO)', 'Punto de venta, productos, trastienda y entrada de NF-e (Manual 42).'],
      ['IA Premium ▼', 'IA Financiera e IA Tributaria (Manuales 36 y 37).'],
      ['Config ▼', 'Empresa, Planes, Uso de la IA y, para el dueño, Equipo (Manuales 38 a 41).'],
      ['Manual', 'Este manual, dentro de Axioma, en los tres idiomas.'],
      ['Términos de Uso / Privacidad', 'Los documentos legales, con cambio de idioma.'],
      ['BANCO', 'Atajo para conectar el banco (Open Finance, Manual 35).'],
      ['Salir', 'Cierra su sesión de forma segura.'],
    ] } },
    { p: 'En el celular, el menú se convierte en el botón **☰** en la esquina superior, con los mismos ítems en lista.' },
    { nota: 'El **cajero** ve solo el PDV: al ingresar, es llevado directamente al punto de venta y no accede a los módulos financieros.' },

    { h1: 'Franjas de aviso en la parte superior' },
    { lista: [
      '**"Completa el registro de tu empresa para habilitar todos los cálculos de Axioma."** Aparece mientras el registro de la empresa esté incompleto. Haga clic en **Completar ahora →** para ir directamente a la pantalla Empresa.',
      '**"Solicitud de aval en el Equipo esperando su decisión."** Aparece para quien puede aprobar una solicitud (por ejemplo, la remoción de alguien de nivel alto). Haga clic para abrir el Equipo y decidir.',
    ] },

    { h1: 'El Asistente de Ayuda' },
    { p: 'En todas las pantallas internas hay un botón verde menta **Ayuda** en la esquina inferior izquierda. Abre un chat que conoce todo este manual y responde preguntas como:' },
    { lista: [
      '"¿Dónde registro un costo fijo?"',
      '"¿Qué pasa si hago clic en Revertir pago?"',
      '"¿Cómo convierto un gasto que se repite en costo fijo?"',
      '"¿A dónde va el valor que registro en Ingresos?"',
    ] },
    { p: 'Cómo funciona:' },
    { numerada: [
      'Haga clic en **Ayuda**. La ventana se abre con tres preguntas sugeridas; haga clic en una o escriba la suya en el campo de abajo y presione Enter (o la flecha).',
      'El asistente lee el manual de la pantalla en la que usted está y los manuales que coinciden con su pregunta, y responde con el camino exacto (menú → pantalla → pestaña → botón) y el paso a paso.',
      'Debajo de la respuesta aparecen botones **Abrir manual NN**: llevan directamente al manual completo de esa pantalla.',
      'Para cerrar, haga clic de nuevo en el botón (ahora con una X). La conversación se guarda mientras no recargue la página.',
    ] },
    { alerta: 'El Asistente de Ayuda **no ve los números de su empresa**: recibe solo la pregunta y el fragmento del manual. Para entender los números (por qué cayó la utilidad, cuánto voy a pagar de impuestos), use la **IA Financiera** o la **IA Tributaria**. No aparece en la pantalla de venta del PDV, para no molestar al cajero.' },

    { h1: 'Lo que existe en casi todas las pantallas' },
    { h2: 'Encabezado del módulo' },
    { p: 'Cada módulo empieza con una tarjeta azul marino con el nombre de la pantalla, una frase que explica para qué sirve y los botones principales:' },
    { tabela: { colunas: ['Botón', 'Qué hace', 'Qué pasa después'], larguras: [2300, 3800, 2926], linhas: [
      ['Exportar PDF', 'Genera un PDF con los datos de la pantalla (tablas, totales e indicadores).', 'El archivo se descarga en el navegador. Mientras se genera, el botón muestra "Gerando..." (Generando). No se altera ningún dato.'],
      ['+ Nuevo (registro, cliente, cuenta...)', 'Abre la ventana de registro del ítem principal del módulo.', 'Solo guarda cuando usted hace clic en Guardar. Cerrar la ventana (X o Cancelar) descarta lo escrito.'],
      ['Tema (Oscuro / Claro)', 'Cambia la apariencia de la pantalla: Oscuro (fondo azul oscuro) o Claro (fondo blanco y tarjetas crema).', 'La elección se guarda en este navegador. Los números no cambian.'],
    ] } },
    { h2: 'Selector de período' },
    { p: 'En los módulos con números a lo largo del tiempo hay un selector con las opciones **Mes actual, Mes anterior, Trimestre actual, Año actual, Últimos 12 meses y Personalizado**. En Personalizado aparecen dos campos de fecha (inicio y fin). Las tarjetas, gráficos y tablas pasan a mostrar solo el período elegido, y las flechas ▲▼ comparan con el período anterior de igual duración.' },
    { h2: 'Marquesina' },
    { p: 'La franja azul marino con texto en movimiento (la marquesina) resume los números más importantes de la pantalla en una línea. Pase el mouse por encima para pausarla.' },
    { h2: 'Tarjetas' },
    { p: 'Todas las tarjetas tienen el mismo efecto al pasar el mouse: el borde se enciende y aparece una franja verde menta en la parte superior. Muchas tarjetas son **clicables**: llevan al módulo de origen de ese número o filtran la lista de la propia pantalla. Cuando una tarjeta es clicable, el cursor se convierte en una manito.' },
    { h2: 'Compartir (Centro de Compartir)' },
    { p: 'El botón **Compartir** abre el Centro de Compartir con estos botones:' },
    { tabela: { colunas: ['Botón', 'Qué pasa'], larguras: [2600, 6426], linhas: [
      ['WhatsApp / Telegram', 'Abre la aplicación (o la versión web) en una nueva pestaña con el resumen ya escrito. Usted elige el contacto y envía.'],
      ['Gmail / Outlook', 'Abre un e-mail nuevo, con asunto y el resumen en el cuerpo. Usted elige el destinatario y envía.'],
      ['E-mail', 'Abre el programa de e-mail predeterminado de su computadora con el resumen.'],
      ['Copiar (resumen)', 'Copia los principales números para pegar donde quiera. El botón muestra "Copiado" por un instante.'],
      ['Copiar (detallado)', 'Copia la lista completa (aparece solo en las pantallas que tienen versión detallada).'],
      ['PDF', 'Cierra el Centro y genera el mismo PDF del botón Exportar PDF.'],
    ] } },
    { p: 'Nada se envía solo: Axioma solo prepara el texto; quien envía es usted. Los valores van siempre con centavos exactos.' },
    { h2: 'Ventanas (modales)' },
    { p: 'Registros, detalles y confirmaciones se abren en ventanas sobre la pantalla. Toda ventana se cierra con la **X** de la esquina o con el botón **Cancelar/Cerrar**. Las acciones que eliminan algo siempre piden confirmación antes; algunas piden también el motivo, que queda registrado en el historial.' },
    { h2: 'Ver Historial' },
    { p: 'En algunos módulos (como Estado de Resultados y Cuentas por Pagar) el botón o la pestaña **Historial** muestra los cierres anteriores o los cambios realizados, con quién los hizo y cuándo.' },

    { h1: 'Quién puede hacer qué (visión general)' },
    { tabela: { colunas: ['Nivel', 'Qué puede'], larguras: [2600, 6426], linhas: [
      ['Propietario (dueño)', 'Todo, incluso la suscripción, el Equipo, transferir la empresa y aprobar lo que exige aval.'],
      ['CEO / Socio / Administrador', 'Casi todo; la remoción de personas de nivel igual o superior puede exigir el aval de alguien por encima.'],
      ['Financiero / Contable / Contador', 'Registrar y modificar en los módulos de su área.'],
      ['Lector / Consultor', 'Ver las pantallas, sin modificar datos (los botones de guardar quedan bloqueados).'],
      ['Cajero', 'Solo el PDV (vender, abrir y cerrar la caja). No ve costos ni módulos financieros.'],
    ] } },
    { p: 'Los detalles de cada pantalla están en la sección "Quién puede hacer qué" de su manual.' },

    { h1: 'Problemas comunes y soluciones' },
    { tabela: { colunas: ['Problema', 'Solución'], larguras: [3400, 5626], linhas: [
      ['Los números aparecen en cero.', 'Revise el selector de período (tal vez esté en un mes sin registros) y si la empresa activa es la correcta. Si la empresa acaba de crearse, empiece por los registros de "El orden correcto para empezar".'],
      ['Los impuestos aparecen en cero o extraños.', 'Complete el régimen tributario en Config → Empresa.'],
      ['Un botón está apagado (no responde).', 'Su nivel de acceso puede ser de solo lectura, o falta completar un campo obligatorio en la ventana. Pase el mouse sobre el botón para ver el aviso.'],
      ['Apareció un mensaje de error al guardar.', 'La ventana sigue abierta con lo que escribió: nada se pierde. Lea el mensaje, corrija y guarde de nuevo. Si se repite, anote el mensaje y contacte al soporte.'],
      ['No encuentro una función.', 'Use el botón Ayuda y pregunte con sus palabras, o busque en el Manual por el nombre del módulo.'],
      ['La pantalla está en otro idioma.', 'Haga clic en PT, EN o ES en el menú superior.'],
      ['La pantalla tardó en abrir.', 'En la primera apertura del día la base de datos puede tardar unos segundos en despertar. Espere y, si es necesario, recargue la página.'],
    ] } },

    { h1: 'Buenas prácticas' },
    { lista: [
      'Registre los ingresos y los costos con frecuencia: cuanto más completos los datos, mejores los análisis.',
      'Conecte el banco en **Open Finance** para traer el extracto automáticamente.',
      'Use **Importar Documentos** para registrar facturas y extractos de una sola vez.',
      'Dé a su equipo solo el acceso necesario y por el menor plazo (Manual 39 — Equipo).',
      'Ante la duda, pregunte al **Asistente de Ayuda** antes de eliminar o modificar algo.',
    ] },
  ],
}

const doc: DocTrilingue = { pt, en, es }
export default doc
