// Fonte única: gera o Word (scripts/gerar-docs) e a página no site.
import type { DocumentoAxioma } from "../tipos"

const doc: DocumentoAxioma = {
  arquivo: '00 - Prólogo, Apresentação e Primeiros Passos.docx',
  titulo: 'Manual 00 — Prólogo e Apresentação',
  subtitulo: 'O que significa Axioma, o que é a plataforma, como pensa o seu motor de inteligência e os primeiros passos',
  info: ['Manual de uso do Axioma AI.Tech  •  Versão 1.0'],
  blocos: [
    { h1: 'Prólogo — o que significa "Axioma"' },
    { h2: 'A origem da palavra' },
    { p: 'A palavra **axioma** vem do grego antigo **ἀξίωμα (axíōma)**, que significa "aquilo que é considerado digno", "aquilo que se recomenda por si mesmo como evidente". Ela deriva do verbo **ἀξιόω (axióō)**, "considerar digno", "julgar válido", que por sua vez nasce de **ἄξιος (áxios)**: "que tem valor", "que está em equilíbrio", "que pesa o mesmo que". É a imagem de uma balança em equilíbrio, em que algo vale exatamente o que diz valer.' },
    { p: 'Na origem, portanto, axioma é aquilo que **tem valor próprio** e **sustenta todo o resto**.' },
    { h2: 'O axioma na ciência' },
    { p: 'Na filosofia grega, **Aristóteles** (século IV a.C.) usou o termo como conceito técnico da lógica: axiomas são as proposições imediatas que é preciso conhecer para aprender qualquer outra coisa, os pontos de partida de toda demonstração. Pouco depois, **Euclides de Alexandria**, nos *Elementos* (cerca de 300 a.C.), construiu toda a geometria a partir de um pequeno conjunto de axiomas e postulados. Dessas poucas verdades de base, por dedução rigorosa, nascem centenas de teoremas.' },
    { p: 'Na matemática e na lógica modernas, a partir de **David Hilbert** (início do século XX), o axioma passou a ser entendido como a **premissa fundamental de um sistema formal**: uma regra de partida, clara e explícita, da qual todo o resto é derivado de forma verificável. A aritmética, a teoria dos conjuntos e a própria ciência da computação se apoiam em sistemas axiomáticos: poucas bases sólidas, raciocínio rigoroso e conclusões que qualquer pessoa pode conferir.' },
    { nota: '**Em resumo:** um axioma é um ponto de partida confiável. Quando as bases são sólidas e o raciocínio é rigoroso, as conclusões também são.' },
    { h2: 'Por que a plataforma se chama Axioma' },
    { p: 'Uma empresa também precisa de axiomas: **números verdadeiros** sobre o que entra, o que sai, o que se deve e o que se tem a receber. Sem eles, toda decisão é um palpite. O Axioma foi construído sobre essa ideia:' },
    { lista: [
      '**Os números são a base, e são reais.** Cada cálculo parte dos lançamentos, documentos e extratos da própria empresa. Nenhum dado fictício é misturado aos seus.',
      '**O raciocínio é rigoroso e conferível.** Impostos, totais, projeções e indicadores são calculados por regras fixas e auditáveis, não por adivinhação.',
      '**A inteligência interpreta, nunca inventa.** A inteligência artificial explica os números e sugere caminhos, e cada valor que ela cita é conferido contra os dados da empresa.',
      '**Os seus dados são seus.** A privacidade e a segurança das informações da empresa e das pessoas vêm antes de qualquer funcionalidade.',
    ] },
    { p: 'Assim como Euclides partiu de poucas verdades para construir toda a geometria, o Axioma parte dos números reais da sua empresa para construir a visão completa do negócio.' },

    { h1: 'Apresentação — a plataforma' },
    { p: 'O **Axioma AI.Tech** é um **CFO digital**: uma plataforma de gestão financeira e inteligência empresarial que reúne em um só lugar tudo o que um diretor financeiro acompanha (receitas, custos, caixa, resultado, dívidas, impostos, clientes, fornecedores, estoque, metas, investimentos e o cenário econômico) e transforma esses dados em decisões.' },
    { p: 'Ele foi pensado para a realidade das empresas brasileiras, do Microempreendedor Individual à empresa de médio porte, e funciona em português, inglês e espanhol.' },
    { h2: 'Nosso objetivo' },
    { p: 'A maioria das pequenas e médias empresas não tem acesso a um diretor financeiro. Decisões importantes, como quanto cobrar, quando contratar, se cabe um empréstimo ou como pagar menos imposto dentro da lei, acabam sendo tomadas no escuro. O objetivo do Axioma é **colocar a inteligência de um CFO experiente ao alcance de qualquer empresa**, disponível a qualquer hora, com os números reais do negócio, em linguagem simples e com respeito total à privacidade de quem usa.' },
    { p: 'Cada tela do Axioma segue o mesmo princípio: mostrar **o que está acontecendo, por que está acontecendo e qual é o próximo passo**.' },

    { h1: 'Inovação: o melhor da tecnologia mundial, pensado para o Brasil' },
    { p: 'O Axioma acompanha de perto o que há de mais avançado em gestão financeira e inteligência artificial nos grandes polos de tecnologia do mundo e traz essas ideias para a realidade da empresa brasileira, com as nossas leis, os nossos impostos e o nosso sistema bancário.' },
    { tabela: { colunas: ['Referência', 'O que inspira', 'Como aparece no Axioma'], larguras: [1900, 3300, 3826], linhas: [
      ['China', 'Plataformas que integram vendas, pagamentos instantâneos e gestão no mesmo lugar, e o uso intenso de dados em tempo real.', 'PDV integrado ao estoque e ao financeiro; pagamento de contas por Pix dentro da plataforma (em preparação); painéis que se atualizam com os dados do dia.'],
      ['Europa', 'Open Banking (com a diretiva PSD2) e privacidade desde a concepção (privacy by design, inspirada na GDPR).', 'Conexão bancária por Open Finance com consentimento do titular; isolamento dos dados por empresa; auditoria do uso de IA sem guardar conteúdo; regras de prazo e lixeira para dados pessoais.'],
      ['Estados Unidos', 'Modelos de linguagem de última geração e ferramentas de planejamento financeiro com IA (FP&A).', 'Motor de orquestração de IA em camadas, com especialistas por área e por setor, conferência automática de números, análises executivas e planos de longo prazo do José.'],
    ] } },
    { h2: 'Funções que levam a gestão além do convencional' },
    { lista: [
      '**Conferência automática de números da IA:** cada valor citado pela inteligência é checado contra os dados reais da empresa antes de chegar a você.',
      '**Nexus e o José:** leitura diária da economia do Brasil e do mundo a partir de fontes públicas oficiais (como Banco Central, IBGE, Banco Mundial e OCDE), cruzada com o setor da sua empresa, com um placar que compara o que foi previsto com o que de fato aconteceu.',
      '**Gêmeo digital do caixa:** simulação do caixa da empresa para testar decisões antes de tomá-las.',
      '**Leitura inteligente de notas fiscais:** XML, PDF ou foto viram lançamentos distribuídos nos módulos certos, sempre com conferência humana antes de gravar.',
      '**Equipe com hierarquia e prazos:** convites presos a um e-mail, códigos de confirmação, acesso temporário e trilha de responsabilidade.',
      '**Tudo em três idiomas:** português, inglês e espanhol em todas as telas.',
    ] },
    { p: 'Nosso compromisso é seguir pesquisando e incorporando inovações sempre que elas tragam ganho real para a empresa, sem abrir mão da segurança e da privacidade de quem usa.' },

    { h1: 'O motor de inteligência do Axioma' },
    { p: 'O coração da plataforma é um **motor de orquestração de inteligência artificial**: um "cérebro" único, usado por todas as telas, construído em camadas para responder como um diretor financeiro de verdade, com segurança e com custo controlado.' },
    { tabela: { colunas: ['Camada', 'O que faz', 'Usa IA?'], larguras: [2200, 5326, 1500], linhas: [
      ['0. Retrato da empresa', 'Reúne os números de todos os módulos: receita, custos pelo nome, impostos pelo regime, lucro, margem, ponto de equilíbrio, caixa, dívidas, contas a receber e a pagar, inadimplência, estoque e obrigações fiscais. Identifica o setor da empresa (toda a classificação CNAE) e gera os alertas da situação.', 'Não'],
      ['1. Triagem', 'Classifica a pergunta como rotina (um fato direto), análise (precisa de raciocínio) ou estratégia (decisão de longo prazo). Primeiro por regras fixas; só em caso de dúvida, por uma IA rápida.', 'Às vezes'],
      ['2. Executor', 'Leva a pergunta ao modelo de IA adequado à complexidade: rotina usa modelos rápidos; análises e estratégias usam os modelos mais avançados. Se a pergunta se mostrar mais difícil do que parecia, ela sobe de nível automaticamente.', 'Sim'],
      ['3. Consulta aos dados', 'Quando precisa de detalhe (por exemplo, as contas que vencem nesta semana ou os maiores devedores), a IA consulta os dados da empresa em modo somente leitura. Ela nunca altera nada.', 'Sim'],
      ['4. Conferência', 'Todo valor em reais citado na resposta é conferido contra os dados reais. O que não puder ser conferido é sinalizado na tela.', 'Não'],
    ] } },
    { h2: 'Especialistas por área e por setor' },
    { p: 'Para cada pergunta, o motor escolhe até três **manuais especialistas** (caixa, custos, precificação, dívida, tributário, cobrança, estoque, crescimento, vendas e economia) e o **manual do setor** da empresa, entre 40 setores que cobrem toda a classificação CNAE. Uma padaria e uma transportadora recebem orientações diferentes, porque o que pesa no caixa de cada uma é diferente.' },
    { h2: 'Os assistentes que você vai encontrar' },
    { tabela: { colunas: ['Onde', 'O que faz'], larguras: [2600, 6426], linhas: [
      ['IA Financeira', 'Conversa sobre a saúde financeira da empresa: score, anomalias, projeções e planos de ação.'],
      ['IA Tributária', 'Compara regimes tributários e explica a carga de impostos e a Reforma Tributária com os seus números.'],
      ['José (Nexus)', 'Acompanha a economia do Brasil e do mundo, explica como cada acontecimento afeta o seu ramo e monta planos de 1 a 10 anos.'],
      ['IA MEI Advisor', 'Responde dúvidas do MEI sobre DAS, teto, imposto de renda e preço.'],
      ['Análises nos módulos', 'O botão Analisar, presente em vários módulos, gera uma análise executiva daquela tela.'],
      ['Leitura de notas', 'Lê notas fiscais em PDF ou foto, distribui os itens nos módulos certos e faz perguntas de conferência antes de gravar.'],
    ] } },
    { h2: 'Compromissos do motor com você' },
    { lista: [
      '**Nunca inventar número:** as contas são feitas pelo Axioma; a IA interpreta.',
      '**Privacidade em primeiro lugar:** a IA recebe só o necessário para responder; os provedores contratados não usam os seus dados para treinar modelos; o registro de auditoria guarda o uso, nunca o conteúdo das conversas.',
      '**Você decide:** a IA orienta e sugere; nenhuma decisão é tomada por ela em seu nome.',
      '**Transparência de consumo:** a tela Config → Uso da IA mostra quantas perguntas foram feitas, quantos números foram conferidos e o custo.',
      '**Sempre funcionar:** se a IA estiver indisponível, as telas continuam respondendo com análises por regras.',
    ] },

    { h1: 'Como usar este manual' },
    { p: 'Este manual é dividido em documentos numerados, um por módulo, na mesma ordem do menu do Axioma. Este primeiro apresenta a plataforma e explica o que é igual em todas as telas. Os seguintes explicam cada módulo em detalhe: para que serve, cada botão, cada card, cada função, o que a inteligência artificial faz ali e o passo a passo das tarefas mais comuns.' },
    { p: 'O mesmo manual está disponível dentro do Axioma, no botão **Manual** do menu do topo.' },
    { h1: 'Primeiros passos' },

    { h1: 'Criar a conta e entrar' },
    { numerada: [
      'Acesse **axiomaai.com.br** e clique em **Criar conta grátis** (ou **Cadastrar com Google**, para usar a sua conta Google).',
      'Informe nome, e-mail e uma senha. Confirme a verificação anti-robô (a caixinha da Cloudflare) quando ela aparecer.',
      'Confirme o e-mail pelo código enviado para a sua caixa de entrada.',
      'Escolha um plano na tela **Planos** para liberar os módulos.',
      'Na primeira entrada, o Axioma cria automaticamente a sua empresa com o nome "Minha Empresa". Complete o cadastro em **Config → Empresa** (a faixa verde no topo da tela lembra você disso).',
    ] },
    { nota: 'Esqueceu a senha? Na tela de login clique em **Esqueceu a senha?**. Você recebe um e-mail para criar uma nova.' },
    { h2: 'Entrar por convite' },
    { p: 'Se alguém da empresa convidou você, abra o link do convite recebido, preencha nome (e CPF, se o acesso for longo), confira quem convidou, aceite os Termos e a LGPD e digite o **código de 8 números** enviado ao seu e-mail. Pronto: você entra direto na empresa que convidou.' },

    { h1: 'O menu do topo' },
    { p: 'O menu fica fixo no alto de todas as telas e é dividido em grupos. Clique em um grupo para abrir a lista de telas dele:' },
    { tabela: { colunas: ['Grupo', 'O que tem dentro'], larguras: [2400, 6626], linhas: [
      ['🏠 Dashboard', 'Visão geral da empresa (Manual 01)'],
      ['🌐 Nexus', 'Inteligência de mercado com o assistente José (Manual 43)'],
      ['🟡 MEI (PRO)', 'Painel MEI, Cockpit, Faturamento, DAS & Obrigações, Reforma Tributária, Precificação MEI, IA MEI Advisor, Imposto de Renda (Manuais 02 a 09)'],
      ['🛒 PDV (PRO)', 'Frente de caixa, catálogo, cadastro de produtos, retaguarda e entrada de NF-e (Manual 42)'],
      ['💰 Financeiro', 'Receitas, Custos Fixos, Custos Variáveis, Fluxo de Caixa, DRE, Endividamento, Tesouraria (Manuais 10 a 16)'],
      ['📒 Contabilidade', 'Contador, Fiscal, Livro Razão, Balancete, DRE Contábil (Manuais 17 a 21)'],
      ['📈 Crescimento', 'Metas, Investimentos, Simulações, Precificação (Manuais 22 a 25)'],
      ['👥 Comercial', 'Clientes, Fornecedores, Contas a Pagar, Estoque, Contas a Receber, Inadimplência (Manuais 26 a 31)'],
      ['🏢 Gestão', 'Centros de Custo, Importar Documentos, Relatórios, Open Finance (Manuais 32 a 35)'],
      ['🤖 IA Premium', 'IA Financeira e IA Tributária (Manuais 36 e 37)'],
      ['⚙️ Config', 'Empresa, Equipe, Planos, Uso da IA (Manuais 38 a 41)'],
      ['🏦 BANCO', 'Atalho para conectar o banco (Open Finance)'],
      ['🇧🇷 🇺🇸 🇪🇸', 'Troca o idioma de todo o Axioma: português, inglês ou espanhol'],
      ['Sair', 'Encerra a sua sessão com segurança'],
    ] } },
    { p: 'No celular, o menu vira o botão **☰** no canto do topo.' },

    { h1: 'Faixas de aviso no topo' },
    { lista: [
      '**Faixa verde-menta "Complete o cadastro da sua empresa"**: aparece enquanto o cadastro da empresa estiver incompleto. Clique para ir direto à tela Empresa.',
      '**Faixa azul-marinho "pedido de aval na Equipe"**: aparece quando alguém pediu um aval que você pode decidir. Clique em **Ver agora** para abrir a Equipe.',
    ] },

    { h1: 'O que existe em quase todas as telas' },
    { h2: 'Cabeçalho do módulo' },
    { p: 'Cada módulo começa com um cartão azul-marinho com o nome da tela, uma frase explicando para que ela serve e os botões principais:' },
    { tabela: { colunas: ['Botão', 'O que faz'], larguras: [2600, 6426], linhas: [
      ['📄 Exportar PDF', 'Gera um PDF com os dados da tela (tabelas, totais e indicadores) para salvar, imprimir ou enviar.'],
      ['+ Novo (lançamento, cliente, conta...)', 'Abre a janela de cadastro do item principal do módulo.'],
      ['Escuro / Tema Claro', 'Troca a aparência da tela. O Escuro tem fundo azul-escuro; o Claro tem fundo branco e cards creme. A escolha fica guardada.'],
    ] } },
    { h2: 'Seletor de período' },
    { p: 'Nos módulos com números ao longo do tempo há um seletor com as opções **Mês atual, Mês anterior, Trimestre atual, Ano atual, Últimos 12 meses e Personalizado** (você escolhe as datas de início e fim). Os cards, gráficos e tabelas passam a mostrar só o período escolhido, e as setas ▲▼ comparam com o período anterior equivalente.' },
    { h2: 'Letreiro' },
    { p: 'A faixa azul-marinho com texto passando (o letreiro) resume os números mais importantes da tela em uma linha. Passe o mouse por cima para pausar a leitura.' },
    { h2: 'Cards com efeito verde-menta' },
    { p: 'Todos os cartões têm um efeito ao passar o mouse: a borda acende e aparece uma faixa verde-menta no topo. Muitos cartões são **clicáveis** e levam ao módulo de origem daquele número ou filtram a lista da própria tela.' },
    { h2: 'Compartilhar (Centro de Compartilhamento)' },
    { p: 'O botão **Compartilhar** abre o Centro de Compartilhamento, onde você escolhe:' },
    { lista: [
      '**Resumo** (os principais números) ou **Detalhado** (lista completa).',
      'O canal: **WhatsApp, Gmail, Outlook, Telegram, outro e-mail** ou **Copiar** (para colar onde quiser).',
    ] },
    { p: 'Os valores compartilhados vão sempre com centavos exatos, sem arredondamento.' },
    { h2: 'Ver Histórico' },
    { p: 'Em alguns módulos (como DRE e Contas a Pagar) o botão **Ver Histórico** mostra os fechamentos anteriores ou as alterações feitas, com quem fez e quando.' },

    { h1: 'Inteligência artificial no Axioma' },
    { lista: [
      'A IA está nas telas IA Financeira, IA Tributária, Nexus (José), na leitura de notas fiscais e em explicações dentro dos módulos.',
      'Ela usa os números reais da sua empresa e **confere os valores** que cita; quando algo não pôde ser conferido, a tela avisa.',
      'Os cálculos de impostos e totais não são feitos pela IA, e sim por regras fixas do Axioma. A IA explica e sugere.',
      'O consumo da IA aparece em **Config → Uso da IA**.',
    ] },

    { h1: 'Boas práticas' },
    { lista: [
      'Lance as receitas e os custos com frequência: quanto mais completos os dados, melhores as análises.',
      'Conecte o banco em **Open Finance** para trazer o extrato automaticamente.',
      'Use **Importar Documentos** para lançar notas fiscais e extratos de uma vez.',
      'Dê à sua equipe só o acesso necessário e pelo menor prazo (veja o Manual 39 — Equipe).',
    ] },
  ],
}

export default doc
