// Fonte única: gera os PDFs (scripts/gerar-pdf.cjs) e a página no site, nos 3 idiomas.
import type { DocumentoAxioma, DocTrilingue } from "../tipos"

const pt: DocumentoAxioma = {
  arquivo: '02 - MEI - Painel MEI.docx',
  titulo: 'Manual 02 — Painel MEI',
  subtitulo: 'A central do Microempreendedor Individual: teto, DAS, quanto do dinheiro é seu e a saúde do negócio',
  info: ['Menu: MEI → Painel MEI  •  Manual de uso do Axioma AI.Tech  •  Versão 2.0'],
  blocos: [
    { h1: 'Para que serve' },
    { p: 'O Painel MEI responde, em uma tela, as perguntas que mais importam para quem é MEI: **quanto faturei, quanto falta para o teto de R$ 81.000 por ano, quanto do dinheiro que entrou é realmente meu, quando vence o DAS e se a minha saúde financeira está boa**.' },
    { nota: 'O MEI é um módulo PRO (selo PRO no menu). Os números vêm das receitas da empresa (as marcadas para contar no teto), das despesas lançadas, das contas a pagar do mês e da configuração feita no botão **Configurar MEI**.' },

    { h1: 'Como chegar' },
    { lista: [
      'Menu do topo → **MEI ▼** → **Painel MEI**.',
      'Atalho **MEI** no fim do Dashboard.',
    ] },

    { h1: 'Antes de começar' },
    { numerada: [
      'Clique em **Configurar MEI** e preencha pelo menos a **Categoria** e a **Data de Abertura** (veja a próxima seção).',
      'Lance as vendas em **MEI → Faturamento** (Manual 04).',
      'Lance as despesas em **Custos Variáveis** e **Custos Fixos** (Manuais 11 e 12) e os boletos em **Contas a Pagar** (Manual 28).',
    ] },

    { h1: 'A janela Configurar MEI' },
    { p: 'Abre pelo botão **Configurar MEI** no cabeçalho. Campos:' },
    { tabela: { colunas: ['Campo', 'Para que serve'], larguras: [3200, 5826], linhas: [
      ['Categoria MEI', 'Serviços, Comércio, Indústria ou Transporte. Ao clicar numa categoria, o Axioma preenche sozinho o valor do DAS de 2026: Serviços R$ 86,05; Comércio e Indústria R$ 82,05; Transporte (MEI caminhoneiro, INSS de 12%) R$ 195,52.'],
      ['Valor DAS Mensal (R$)', 'O valor do boleto mensal. Ajuste se o seu for diferente (por exemplo, Comércio e Serviços juntos: R$ 87,05).'],
      ['Dia de Vencimento do DAS', 'Normalmente dia 20. Usado nos avisos e no Guardião da Reserva.'],
      ['Data de Abertura do MEI', 'Calcula o teto proporcional no ano em que o MEI foi aberto (R$ 6.750 por mês ativo).'],
      ['Nome / Razão Social, CNPJ, Atividade Principal (CNAE)', 'Identificam o seu MEI nos relatórios e nos PDFs.'],
      ['Seus clientes são principalmente', 'Empresas (B2B), Pessoas físicas (B2C) ou Ambos. Ajuda a IA MEI Advisor e a Reforma Tributária a orientar certo.'],
      ['Pró-labore Desejado (R$)', 'Quanto você gostaria de retirar por mês. O painel compara com o pró-labore seguro.'],
      ['Reserva de Emergência (%)', 'Quanto da sobra você quer guardar como reserva.'],
    ] } },
    { p: '**Salvar** grava a configuração e recarrega o painel com os novos números. **Cancelar** (ou o X) fecha sem mudar nada. Se a gravação falhar, aparece a mensagem de erro e a janela continua aberta com o que você digitou.' },

    { h1: 'Mapa da tela (de cima para baixo)' },
    { numerada: [
      '**Cabeçalho** com Exportar PDF, Configurar MEI, Compartilhar e tema.',
      '**Letreiro** com os principais números do MEI.',
      '**Cartões principais:** Faturamento, Limite Restante e DAS Mensal.',
      '**O que é seu de verdade (Cofre Inteligente)** e o aviso **Retirada acima do seguro**, quando for o caso.',
      '**Guardião da Reserva** do DAS.',
      '**Radar do Teto** e o gráfico **Progresso do Teto no Tempo**.',
      '**Evolução de Ganhos** com três métricas.',
      '**Seu dinheiro em 3 linhas** (Entrou, Saiu, Sobra), clicáveis.',
      '**Fluxo de Caixa Visual** e **Composição do Cofre** (gráficos).',
      '**Score de Saúde do MEI** com quatro partes.',
      '**Gastos que parecem pessoais**, quando houver.',
      '**Resumo Anual MEI** e **Acesso rápido**.',
    ] },

    { h1: 'Botões e ações' },
    { tabela: { colunas: ['Botão', 'O que faz', 'O que acontece depois'], larguras: [2300, 3700, 3026], linhas: [
      ['Exportar PDF', 'Gera o PDF do painel com os números atuais.', 'O arquivo é baixado e aparece o aviso "PDF pronto". Nada é alterado.'],
      ['Configurar MEI', 'Abre a janela de configuração.', 'Só grava ao clicar em Salvar.'],
      ['Compartilhar', 'Abre o Centro de Compartilhamento com o resumo do MEI.', 'Você escolhe o canal e envia; o botão PDF dali gera o mesmo PDF.'],
      ['Tema (Escuro / Claro)', 'Troca a aparência.', 'Fica guardado no navegador.'],
      ['Entrou (Seu dinheiro em 3 linhas)', 'Atalho.', 'Abre MEI → Faturamento.'],
      ['Saiu', 'Atalho.', 'Abre Custos Variáveis.'],
      ['Sobra', 'Atalho.', 'Abre Fluxo de Caixa.'],
      ['Acesso rápido', 'Seis atalhos: Faturamento, DAS & Obrigações, Reforma Tributária, Precificação, IA MEI Advisor e Imposto de Renda.', 'Abre a tela escolhida.'],
    ] } },

    { h1: 'O que cada parte mostra' },
    { h2: 'Cartões principais' },
    { tabela: { colunas: ['Cartão', 'Como é calculado'], larguras: [2600, 6426], linhas: [
      ['Faturamento', 'Soma das receitas do ano atual que contam para o teto do MEI (as marcadas para não contar ficam de fora; veja o Manual 04).'],
      ['Limite Restante', 'Teto do ano (R$ 81.000, ou o proporcional no ano de abertura) menos o faturamento. Nunca fica negativo.'],
      ['DAS Mensal', 'O valor configurado em Configurar MEI.'],
    ] } },
    { h2: 'O que é seu de verdade (Cofre Inteligente)' },
    { p: 'Pega a sobra do mês (o que entrou menos o que saiu) e separa o que **já tem dono**:' },
    { lista: [
      '**DAS do mês** — não é seu, vence no dia configurado.',
      '**Reserva de IRPF** — guardando para a declaração do ano (Manual 09).',
      '**Contas a pagar do período** — boletos em aberto que vencem neste mês.',
      '**Reserva de emergência** — a porcentagem que você configurou.',
      '**Seu pró-labore seguro este mês** — o que sobra e pode ser retirado sem risco.',
    ] },
    { p: 'Também mostra "Guarde deste valor", "Você deveria ter guardado até agora" e compara o pró-labore desejado com o seguro.' },
    { h2: 'Retirada acima do seguro' },
    { p: 'Aviso que aparece quando a sobra não cobre DAS, IRPF e compromissos, ou quando gastos que parecem pessoais passam do pró-labore seguro. Recomenda não retirar dinheiro naquele momento.' },
    { h2: 'Guardião da Reserva' },
    { p: 'Mostra quanto da reserva do DAS já foi usado, quantos dias faltam para repor até o vencimento e quanto o atraso custaria: multa de 0,33% ao dia, limitada a 20%, mais juros pela Selic do dia (buscada do Banco Central). O cálculo usa os lançamentos do sistema, não o saldo do banco.' },
    { h2: 'Radar do Teto' },
    { p: 'Semáforo do limite anual: **Confortável** (verde), **Atenção** e **Risco de estouro**. Mostra em quantos meses, no ritmo atual, você atinge o teto, explica a consequência (deixar de ser MEI e virar ME, com imposto em % da receita) e dá duas saídas: segurar o faturamento até o fim do ano ou preparar a migração para ME com antecedência.' },
    { h2: 'Progresso do Teto no Tempo' },
    { p: 'Gráfico do faturamento acumulado mês a mês contra a linha do teto.' },
    { h2: 'Evolução de Ganhos' },
    { p: 'Gráfico da receita mês a mês e três métricas: **Ticket médio**, **Recebimentos no mês** e **Maior receita do mês**, cada uma marcada "acima da sua média" ou "abaixo da sua média".' },
    { h2: 'Seu dinheiro em 3 linhas' },
    { p: '**Entrou**, **Saiu** e **Sobra** do mês, e quantos dias faltam para o DAS. Cada linha é um atalho (veja Botões e ações).' },
    { h2: 'Score de Saúde do MEI' },
    { tabela: { colunas: ['Parte', 'O que avalia'], larguras: [2400, 6626], linhas: [
      ['Financeiro', 'Se a receita está crescendo mês a mês.'],
      ['Fiscal', 'Se DAS, DASN e IR estão em dia (status marcado em DAS & Obrigações).'],
      ['Teto', 'A distância até o limite anual.'],
      ['Fluxo', 'Se sobra dinheiro depois de pagar os custos do mês.'],
    ] } },
    { h2: 'Gastos que parecem pessoais' },
    { p: 'Lista despesas lançadas que parecem gastos da pessoa física (supermercado, farmácia, lazer). Separar o pessoal do empresarial protege você numa fiscalização, porque a Receita cruza CPF e CNPJ cada vez mais. Para corrigir, abra o lançamento no módulo de origem e ajuste ou exclua.' },
    { h2: 'Resumo Anual MEI' },
    { p: 'Total de receitas lançadas, média mensal dos últimos 6 meses e projeção do ano.' },

    { h1: 'Passo a passo' },
    { h2: 'Rotina mensal do MEI' },
    { numerada: [
      'Lance as vendas em **MEI → Faturamento** durante o mês.',
      'Abra o Painel MEI e confira o **Radar do Teto**.',
      'Veja o **pró-labore seguro** antes de retirar dinheiro para você.',
      'Pague o DAS até o vencimento e marque como pago em **DAS & Obrigações** (Manual 05).',
      'Se aparecer "Gastos que parecem pessoais", revise esses lançamentos.',
    ] },
    { h2: 'Mudar a categoria do MEI' },
    { numerada: [
      'Clique em **Configurar MEI**.',
      'Clique na nova categoria: o valor do DAS muda sozinho.',
      'Confira o valor e clique em **Salvar**.',
    ] },

    { h2: 'Abrir minha empresa (MEI ou ME)' },
    { numerada: [
      'No fim do Painel MEI, no cartão **Abrir minha empresa**, escolha **Abrir MEI** ou **Abrir ME (Simples)**.',
      'Siga os passos: cada um tem o botão **Abrir portal oficial** (gov.br, REDESIM, Portal do Simples). Abrir MEI é gratuito.',
      'Quando o CNPJ sair, digite em **Já tenho CNPJ** e clique em **Buscar na Receita e preencher**.',
      'A janela Configurar MEI abre com CNPJ, razão social, atividade e data de abertura preenchidos: confira e clique em **Salvar**.',
    ] },
    { nota: 'ME nova tem prazo para optar pelo Simples Nacional: até 30 dias da última inscrição (municipal ou estadual), sem passar de 60 dias da abertura do CNPJ (Resolução CGSN 140/2018, art. 6º). Regra conferida em 10/10/2026.' },

    { h1: 'Ligações com outros módulos' },
    { tabela: { colunas: ['Vem de', 'Para quê'], larguras: [3000, 6026], linhas: [
      ['Receitas / MEI → Faturamento', 'Faturamento, teto, evolução de ganhos.'],
      ['Custos Variáveis e Custos Fixos', '"Saiu", sobra do mês e gastos que parecem pessoais.'],
      ['Contas a Pagar', 'Compromissos do mês no Cofre.'],
      ['DAS & Obrigações', 'Status do DAS, DASN e IRPF no Score.'],
      ['Banco Central (Selic)', 'Juros do atraso no Guardião da Reserva.'],
    ] } },
    { p: 'A configuração salva aqui é usada por todas as telas do MEI (DAS, Reforma, Precificação, IA MEI Advisor e Imposto de Renda).' },

    { h1: 'Quem pode fazer o quê' },
    { p: 'Quem tem acesso ao MEI vê o painel. Salvar a configuração exige permissão de escrita na empresa; perfis somente leitura veem tudo, mas a gravação é recusada.' },

    { h1: 'Problemas comuns e soluções' },
    { tabela: { colunas: ['Problema', 'Solução'], larguras: [3400, 5626], linhas: [
      ['O faturamento não bate com o que vendi.', 'Confira em MEI → Faturamento se alguma receita está marcada para não contar no teto, e se as datas estão no ano certo.'],
      ['O teto aparece menor que R$ 81.000.', 'É o teto proporcional do ano de abertura (R$ 6.750 por mês ativo). Confira a Data de Abertura em Configurar MEI.'],
      ['O pró-labore seguro está negativo.', 'A sobra do mês não cobre DAS, IRPF e contas. O ideal é não retirar dinheiro até a situação melhorar.'],
      ['O Score Fiscal está baixo mesmo pagando o DAS.', 'Marque o DAS como pago em DAS & Obrigações; o painel lê esse status.'],
      ['Erro ao salvar a configuração.', 'A janela continua aberta. Confira se os valores são números (use vírgula ou ponto) e tente de novo.'],
    ] } },
  ],
}

const en: DocumentoAxioma = {
  arquivo: '02 - MEI - MEI Dashboard.docx',
  titulo: 'Manual 02 — MEI Dashboard',
  subtitulo: 'The hub for the Individual Micro-Entrepreneur (MEI): revenue cap, DAS, how much of the money is yours and business health',
  info: ['Menu: MEI → MEI Dashboard  •  Axioma AI.Tech user manual  •  Version 2.0'],
  blocos: [
    { h1: 'What it is for' },
    { p: 'MEI is the Brazilian Individual Micro-Entrepreneur regime. The MEI Dashboard answers, on one screen, the questions that matter most to an MEI: **how much did I bill, how much is left before the R$ 81,000 annual cap, how much of the money that came in is really mine, when the DAS (the monthly MEI tax slip) is due, and whether my financial health is good**.' },
    { nota: 'MEI is a PRO module (PRO tag on the menu). The figures come from the company\'s revenues (those marked to count toward the cap), the expenses entered, the month\'s payables and the setup made with the **Configure MEI** button.' },

    { h1: 'How to get there' },
    { lista: [
      'Top menu → **MEI ▼** → **MEI Dashboard**.',
      '**MEI** shortcut at the end of the Dashboard.',
    ] },

    { h1: 'Before you start' },
    { numerada: [
      'Click **Configure MEI** and fill in at least the **Category** and the **Opening Date** (see the next section).',
      'Enter your sales in **MEI → Revenue** (Manual 04).',
      'Enter expenses in **Variable Costs** and **Fixed Costs** (Manuals 11 and 12) and bills in **Accounts Payable** (Manual 28).',
    ] },

    { h1: 'The Configure MEI window' },
    { p: 'Opens with the **Configure MEI** button in the header. Fields:' },
    { tabela: { colunas: ['Field', 'What it is for'], larguras: [3200, 5826], linhas: [
      ['MEI Category', 'Services, Commerce, Industry or Transport. When you click a category, Axioma fills in the 2026 DAS amount: Services R$ 86.05; Commerce and Industry R$ 82.05; Transport (MEI truck driver, 12% INSS) R$ 195.52.'],
      ['Monthly DAS Amount (R$)', 'The monthly slip amount. Adjust it if yours is different (for example, Commerce and Services together: R$ 87.05).'],
      ['DAS Due Day', 'Usually the 20th. Used in notices and in the Reserve Guardian.'],
      ['MEI Opening Date', 'Calculates the proportional cap in the year the MEI was opened (R$ 6,750 per active month).'],
      ['Name / Company Name, CNPJ, Main Activity (CNAE)', 'Identify your MEI in reports and PDFs.'],
      ['Your clients are mainly', 'Companies (B2B), Individuals (B2C) or Both. Helps the AI MEI Advisor and Tax Reform give the right guidance.'],
      ['Desired Owner\'s Draw (R$)', 'How much you would like to take out per month. The dashboard compares it with the safe draw.'],
      ['Emergency Reserve (%)', 'How much of the surplus you want to keep as a reserve.'],
    ] } },
    { p: '**Save** stores the setup and reloads the dashboard with the new figures. **Cancel** (or the X) closes without changing anything. If saving fails, the error message appears and the window stays open with what you typed.' },

    { h1: 'Screen map (top to bottom)' },
    { numerada: [
      '**Header** with Export PDF, Configure MEI, Share and theme.',
      '**Ticker** with the main MEI figures.',
      '**Main cards:** Revenue, Remaining Limit and Monthly DAS.',
      '**What is really yours (Smart Vault)** and the **Withdrawal above safe** notice, when applicable.',
      '**Reserve Guardian** for the DAS.',
      '**Cap Radar** and the **Cap Progress over Time** chart.',
      '**Earnings Evolution** with three metrics.',
      '**Your money in 3 lines** (In, Out, Surplus), clickable.',
      '**Visual Cash Flow** and **Vault Composition** (charts).',
      '**MEI Health Score** with four parts.',
      '**Expenses that look personal**, when there are any.',
      '**MEI Annual Summary** and **Quick access**.',
    ] },

    { h1: 'Buttons and actions' },
    { tabela: { colunas: ['Button', 'What it does', 'What happens next'], larguras: [2300, 3700, 3026], linhas: [
      ['Export PDF', 'Generates the dashboard PDF with the current figures.', 'The file is downloaded and the notice "PDF ready" appears. Nothing is changed.'],
      ['Configure MEI', 'Opens the setup window.', 'It only saves when you click Save.'],
      ['Share', 'Opens the Sharing Center with the MEI summary.', 'You choose the channel and send; its PDF button generates the same PDF.'],
      ['Theme (Dark / Light)', 'Changes the look.', 'Kept in the browser.'],
      ['In (Your money in 3 lines)', 'Shortcut.', 'Opens MEI → Revenue.'],
      ['Out', 'Shortcut.', 'Opens Variable Costs.'],
      ['Surplus', 'Shortcut.', 'Opens Cash Flow.'],
      ['Quick access', 'Six shortcuts: Revenue, DAS & Obligations, Tax Reform, Pricing, AI MEI Advisor and Income Tax.', 'Opens the chosen screen.'],
    ] } },

    { h1: 'What each part shows' },
    { h2: 'Main cards' },
    { tabela: { colunas: ['Card', 'How it is calculated'], larguras: [2600, 6426], linhas: [
      ['Revenue', 'Sum of the current year\'s revenues that count toward the MEI cap (those marked not to count are left out; see Manual 04).'],
      ['Remaining Limit', 'The year\'s cap (R$ 81,000, or the proportional one in the opening year) minus revenue. Never negative.'],
      ['Monthly DAS', 'The amount set in Configure MEI.'],
    ] } },
    { h2: 'What is really yours (Smart Vault)' },
    { p: 'Takes the month\'s surplus (what came in minus what went out) and separates what **already has an owner**:' },
    { lista: [
      '**This month\'s DAS** — not yours, due on the configured day.',
      '**Income tax (IRPF) reserve** — saving for the year\'s return (Manual 09).',
      '**Payables for the period** — open bills due this month.',
      '**Emergency reserve** — the percentage you configured.',
      '**Your safe owner\'s draw this month** — what is left and can be taken out without risk.',
    ] },
    { p: 'It also shows "Set aside from this amount", "You should have set aside by now" and compares the desired draw with the safe one.' },
    { h2: 'Withdrawal above safe' },
    { p: 'A notice that appears when the surplus does not cover DAS, income tax and commitments, or when expenses that look personal exceed the safe draw. It recommends not taking money out at that moment.' },
    { h2: 'Reserve Guardian' },
    { p: 'Shows how much of the DAS reserve has been used, how many days are left to replenish it before the due date and how much a delay would cost: a fine of 0.33% per day, capped at 20%, plus interest at the day\'s Selic rate (fetched from the Central Bank of Brazil). The calculation uses the system\'s entries, not the bank balance.' },
    { h2: 'Cap Radar' },
    { p: 'A traffic light for the annual limit: **Comfortable** (green), **Attention** and **Risk of exceeding**. It shows in how many months, at the current pace, you will reach the cap, explains the consequence (no longer being an MEI and becoming an ME, with tax as a % of revenue) and gives two ways out: hold revenue until year-end or prepare the migration to ME in advance.' },
    { h2: 'Cap Progress over Time' },
    { p: 'Chart of cumulative revenue month by month against the cap line.' },
    { h2: 'Earnings Evolution' },
    { p: 'Chart of revenue month by month and three metrics: **Average ticket**, **Receipts this month** and **Largest revenue this month**, each marked "above your average" or "below your average".' },
    { h2: 'Your money in 3 lines' },
    { p: '**In**, **Out** and **Surplus** for the month, and how many days are left until the DAS. Each line is a shortcut (see Buttons and actions).' },
    { h2: 'MEI Health Score' },
    { tabela: { colunas: ['Part', 'What it evaluates'], larguras: [2400, 6626], linhas: [
      ['Financial', 'Whether revenue is growing month over month.'],
      ['Tax', 'Whether DAS, DASN (annual MEI return) and income tax are up to date (status marked in DAS & Obligations).'],
      ['Cap', 'The distance to the annual limit.'],
      ['Flow', 'Whether money is left after paying the month\'s costs.'],
    ] } },
    { h2: 'Expenses that look personal' },
    { p: 'Lists entered expenses that look like personal spending (supermarket, pharmacy, leisure). Separating personal from business spending protects you in an audit, since the Brazilian tax authority increasingly cross-checks CPF and CNPJ. To fix it, open the entry in its source module and adjust or delete it.' },
    { h2: 'MEI Annual Summary' },
    { p: 'Total revenues entered, monthly average of the last 6 months and the year\'s projection.' },

    { h1: 'Step by step' },
    { h2: 'MEI monthly routine' },
    { numerada: [
      'Enter sales in **MEI → Revenue** during the month.',
      'Open the MEI Dashboard and check the **Cap Radar**.',
      'Check the **safe owner\'s draw** before taking money out for yourself.',
      'Pay the DAS by the due date and mark it as paid in **DAS & Obligations** (Manual 05).',
      'If "Expenses that look personal" appears, review those entries.',
    ] },
    { h2: 'Change the MEI category' },
    { numerada: [
      'Click **Configure MEI**.',
      'Click the new category: the DAS amount changes automatically.',
      'Check the amount and click **Save**.',
    ] },

    { h2: 'Open my company (MEI or ME)' },
    { numerada: [
      'At the end of the MEI Panel, on the **Open my company** card, choose **Open MEI** or **Open ME (Simples)**.',
      'Follow the steps: each has an **Open official portal** button (gov.br, REDESIM, Simples Portal). Opening an MEI is free.',
      'When the CNPJ is out, type it in **I already have a CNPJ** and click **Fetch and fill in**.',
      'The Configure MEI window opens with CNPJ, company name, activity and opening date filled in: check and click **Save**.',
    ] },
    { nota: 'A new ME has a deadline to opt into Simples Nacional: up to 30 days from the last registration (city or state), no more than 60 days from the CNPJ opening (CGSN Resolution 140/2018, art. 6). Rule checked on 10/10/2026.' },

    { h1: 'Links with other modules' },
    { tabela: { colunas: ['Comes from', 'Used for'], larguras: [3000, 6026], linhas: [
      ['Revenue / MEI → Revenue', 'Revenue, cap, earnings evolution.'],
      ['Variable Costs and Fixed Costs', '"Out", the month\'s surplus and expenses that look personal.'],
      ['Accounts Payable', 'The month\'s commitments in the Vault.'],
      ['DAS & Obligations', 'DAS, DASN and income tax status in the Score.'],
      ['Central Bank of Brazil (Selic)', 'Late-payment interest in the Reserve Guardian.'],
    ] } },
    { p: 'The setup saved here is used by every MEI screen (DAS, Tax Reform, Pricing, AI MEI Advisor and Income Tax).' },

    { h1: 'Who can do what' },
    { p: 'Anyone with access to MEI sees the dashboard. Saving the setup requires write permission in the company; read-only profiles see everything, but saving is refused.' },

    { h1: 'Common problems and solutions' },
    { tabela: { colunas: ['Problem', 'Solution'], larguras: [3400, 5626], linhas: [
      ['Revenue does not match what I sold.', 'Check in MEI → Revenue whether any revenue is marked not to count toward the cap, and whether the dates are in the right year.'],
      ['The cap shows less than R$ 81,000.', 'It is the proportional cap for the opening year (R$ 6,750 per active month). Check the Opening Date in Configure MEI.'],
      ['The safe owner\'s draw is negative.', 'The month\'s surplus does not cover DAS, income tax and bills. Ideally, do not take money out until things improve.'],
      ['The Tax Score is low even though I pay the DAS.', 'Mark the DAS as paid in DAS & Obligations; the dashboard reads that status.'],
      ['Error when saving the setup.', 'The window stays open. Check that the amounts are numbers (comma or period) and try again.'],
    ] } },
  ],
}

const es: DocumentoAxioma = {
  arquivo: '02 - MEI - Panel MEI.docx',
  titulo: 'Manual 02 — Panel MEI',
  subtitulo: 'La central del Microemprendedor Individual (MEI): tope, DAS, cuánto del dinero es suyo y la salud del negocio',
  info: ['Menú: MEI → Panel MEI  •  Manual de uso de Axioma AI.Tech  •  Versión 2.0'],
  blocos: [
    { h1: 'Para qué sirve' },
    { p: 'El MEI es el régimen brasileño del Microemprendedor Individual. El Panel MEI responde, en una pantalla, las preguntas que más importan para quien es MEI: **cuánto facturé, cuánto falta para el tope de R$ 81.000 por año, cuánto del dinero que entró es realmente mío, cuándo vence el DAS (la boleta mensual del MEI) y si mi salud financiera está bien**.' },
    { nota: 'El MEI es un módulo PRO (sello PRO en el menú). Los números vienen de los ingresos de la empresa (los marcados para contar en el tope), de los gastos registrados, de las cuentas por pagar del mes y de la configuración hecha en el botón **Configurar MEI**.' },

    { h1: 'Cómo llegar' },
    { lista: [
      'Menú superior → **MEI ▼** → **Panel MEI**.',
      'Atajo **MEI** al final del Panel principal (Dashboard).',
    ] },

    { h1: 'Antes de empezar' },
    { numerada: [
      'Haga clic en **Configurar MEI** y complete al menos la **Categoría** y la **Fecha de Apertura** (vea la próxima sección).',
      'Registre las ventas en **MEI → Facturación** (Manual 04).',
      'Registre los gastos en **Costos Variables** y **Costos Fijos** (Manuales 11 y 12) y las boletas en **Cuentas por Pagar** (Manual 28).',
    ] },

    { h1: 'La ventana Configurar MEI' },
    { p: 'Se abre con el botón **Configurar MEI** del encabezado. Campos:' },
    { tabela: { colunas: ['Campo', 'Para qué sirve'], larguras: [3200, 5826], linhas: [
      ['Categoría MEI', 'Servicios, Comercio, Industria o Transporte. Al hacer clic en una categoría, Axioma completa solo el valor del DAS de 2026: Servicios R$ 86,05; Comercio e Industria R$ 82,05; Transporte (MEI camionero, INSS del 12%) R$ 195,52.'],
      ['Valor DAS Mensual (R$)', 'El valor de la boleta mensual. Ajústelo si el suyo es diferente (por ejemplo, Comercio y Servicios juntos: R$ 87,05).'],
      ['Día de Vencimiento del DAS', 'Normalmente el día 20. Se usa en los avisos y en el Guardián de la Reserva.'],
      ['Fecha de Apertura del MEI', 'Calcula el tope proporcional en el año en que se abrió el MEI (R$ 6.750 por mes activo).'],
      ['Nombre / Razón Social, CNPJ, Actividad Principal (CNAE)', 'Identifican su MEI en los informes y PDFs.'],
      ['Sus clientes son principalmente', 'Empresas (B2B), Personas físicas (B2C) o Ambos. Ayuda a la IA Advisor MEI y a la Reforma Tributaria a orientar bien.'],
      ['Retiro Deseado (R$)', 'Cuánto le gustaría retirar por mes. El panel lo compara con el retiro seguro.'],
      ['Reserva de Emergencia (%)', 'Cuánto del sobrante quiere guardar como reserva.'],
    ] } },
    { p: '**Guardar** graba la configuración y recarga el panel con los nuevos números. **Cancelar** (o la X) cierra sin cambiar nada. Si la grabación falla, aparece el mensaje de error y la ventana sigue abierta con lo que escribió.' },

    { h1: 'Mapa de la pantalla (de arriba abajo)' },
    { numerada: [
      '**Encabezado** con Exportar PDF, Configurar MEI, Compartir y tema.',
      '**Marquesina** con los principales números del MEI.',
      '**Tarjetas principales:** Facturación, Límite Restante y DAS Mensual.',
      '**Lo que es suyo de verdad (Cofre Inteligente)** y el aviso **Retiro por encima del seguro**, cuando corresponda.',
      '**Guardián de la Reserva** del DAS.',
      '**Radar del Tope** y el gráfico **Progreso del Tope en el Tiempo**.',
      '**Evolución de Ganancias** con tres métricas.',
      '**Su dinero en 3 líneas** (Entró, Salió, Sobra), clicables.',
      '**Flujo de Caja Visual** y **Composición del Cofre** (gráficos).',
      '**Puntuación de Salud del MEI** con cuatro partes.',
      '**Gastos que parecen personales**, cuando los haya.',
      '**Resumen Anual MEI** y **Acceso rápido**.',
    ] },

    { h1: 'Botones y acciones' },
    { tabela: { colunas: ['Botón', 'Qué hace', 'Qué pasa después'], larguras: [2300, 3700, 3026], linhas: [
      ['Exportar PDF', 'Genera el PDF del panel con los números actuales.', 'El archivo se descarga y aparece el aviso "PDF listo". Nada se altera.'],
      ['Configurar MEI', 'Abre la ventana de configuración.', 'Solo graba al hacer clic en Guardar.'],
      ['Compartir', 'Abre el Centro de Compartir con el resumen del MEI.', 'Usted elige el canal y envía; su botón PDF genera el mismo PDF.'],
      ['Tema (Oscuro / Claro)', 'Cambia la apariencia.', 'Se guarda en el navegador.'],
      ['Entró (Su dinero en 3 líneas)', 'Atajo.', 'Abre MEI → Facturación.'],
      ['Salió', 'Atajo.', 'Abre Costos Variables.'],
      ['Sobra', 'Atajo.', 'Abre Flujo de Caja.'],
      ['Acceso rápido', 'Seis atajos: Facturación, DAS & Obligaciones, Reforma Tributaria, Precios, IA Advisor MEI e Impuesto a la Renta.', 'Abre la pantalla elegida.'],
    ] } },

    { h1: 'Qué muestra cada parte' },
    { h2: 'Tarjetas principales' },
    { tabela: { colunas: ['Tarjeta', 'Cómo se calcula'], larguras: [2600, 6426], linhas: [
      ['Facturación', 'Suma de los ingresos del año actual que cuentan para el tope del MEI (los marcados para no contar quedan fuera; vea el Manual 04).'],
      ['Límite Restante', 'Tope del año (R$ 81.000, o el proporcional en el año de apertura) menos la facturación. Nunca es negativo.'],
      ['DAS Mensual', 'El valor configurado en Configurar MEI.'],
    ] } },
    { h2: 'Lo que es suyo de verdad (Cofre Inteligente)' },
    { p: 'Toma el sobrante del mes (lo que entró menos lo que salió) y separa lo que **ya tiene dueño**:' },
    { lista: [
      '**DAS del mes** — no es suyo, vence el día configurado.',
      '**Reserva de impuesto a la renta (IRPF)** — guardando para la declaración del año (Manual 09).',
      '**Cuentas por pagar del período** — boletas abiertas que vencen este mes.',
      '**Reserva de emergencia** — el porcentaje que configuró.',
      '**Su retiro seguro este mes** — lo que sobra y puede retirarse sin riesgo.',
    ] },
    { p: 'También muestra "Guarde de este valor", "Debería haber guardado hasta ahora" y compara el retiro deseado con el seguro.' },
    { h2: 'Retiro por encima del seguro' },
    { p: 'Aviso que aparece cuando el sobrante no cubre DAS, impuesto a la renta y compromisos, o cuando gastos que parecen personales superan el retiro seguro. Recomienda no retirar dinero en ese momento.' },
    { h2: 'Guardián de la Reserva' },
    { p: 'Muestra cuánto de la reserva del DAS ya se usó, cuántos días faltan para reponerla hasta el vencimiento y cuánto costaría el atraso: multa del 0,33% por día, limitada al 20%, más intereses según la tasa Selic del día (obtenida del Banco Central de Brasil). El cálculo usa los registros del sistema, no el saldo del banco.' },
    { h2: 'Radar del Tope' },
    { p: 'Semáforo del límite anual: **Cómodo** (verde), **Atención** y **Riesgo de exceso**. Muestra en cuántos meses, al ritmo actual, alcanzará el tope, explica la consecuencia (dejar de ser MEI y pasar a ME, con impuesto en % de los ingresos) y da dos salidas: frenar la facturación hasta fin de año o preparar la migración a ME con anticipación.' },
    { h2: 'Progreso del Tope en el Tiempo' },
    { p: 'Gráfico de la facturación acumulada mes a mes contra la línea del tope.' },
    { h2: 'Evolución de Ganancias' },
    { p: 'Gráfico de los ingresos mes a mes y tres métricas: **Ticket promedio**, **Cobros del mes** y **Mayor ingreso del mes**, cada una marcada "por encima de su promedio" o "por debajo de su promedio".' },
    { h2: 'Su dinero en 3 líneas' },
    { p: '**Entró**, **Salió** y **Sobra** del mes, y cuántos días faltan para el DAS. Cada línea es un atajo (vea Botones y acciones).' },
    { h2: 'Puntuación de Salud del MEI' },
    { tabela: { colunas: ['Parte', 'Qué evalúa'], larguras: [2400, 6626], linhas: [
      ['Financiero', 'Si los ingresos crecen mes a mes.'],
      ['Fiscal', 'Si DAS, DASN (declaración anual del MEI) e impuesto a la renta están al día (estado marcado en DAS & Obligaciones).'],
      ['Tope', 'La distancia hasta el límite anual.'],
      ['Flujo', 'Si sobra dinero después de pagar los costos del mes.'],
    ] } },
    { h2: 'Gastos que parecen personales' },
    { p: 'Lista gastos registrados que parecen gastos de la persona física (supermercado, farmacia, ocio). Separar lo personal de lo empresarial lo protege en una fiscalización, porque la Receita Federal cruza CPF y CNPJ cada vez más. Para corregir, abra el registro en su módulo de origen y ajústelo o elimínelo.' },
    { h2: 'Resumen Anual MEI' },
    { p: 'Total de ingresos registrados, promedio mensual de los últimos 6 meses y proyección del año.' },

    { h1: 'Paso a paso' },
    { h2: 'Rutina mensual del MEI' },
    { numerada: [
      'Registre las ventas en **MEI → Facturación** durante el mes.',
      'Abra el Panel MEI y revise el **Radar del Tope**.',
      'Mire el **retiro seguro** antes de retirar dinero para usted.',
      'Pague el DAS hasta el vencimiento y márquelo como pagado en **DAS & Obligaciones** (Manual 05).',
      'Si aparece "Gastos que parecen personales", revise esos registros.',
    ] },
    { h2: 'Cambiar la categoría del MEI' },
    { numerada: [
      'Haga clic en **Configurar MEI**.',
      'Haga clic en la nueva categoría: el valor del DAS cambia solo.',
      'Revise el valor y haga clic en **Guardar**.',
    ] },

    { h2: 'Abrir mi empresa (MEI o ME)' },
    { numerada: [
      'Al final del Panel MEI, en la tarjeta **Abrir mi empresa**, elija **Abrir MEI** o **Abrir ME (Simples)**.',
      'Siga los pasos: cada uno tiene el botón **Abrir portal oficial** (gov.br, REDESIM, Portal del Simples). Abrir un MEI es gratuito.',
      'Cuando salga el CNPJ, escríbalo en **Ya tengo CNPJ** y haga clic en **Buscar y llenar**.',
      'La ventana Configurar MEI se abre con CNPJ, razón social, actividad y fecha de apertura llenados: revise y haga clic en **Guardar**.',
    ] },
    { nota: 'Una ME nueva tiene plazo para optar por el Simples Nacional: hasta 30 días de la última inscripción (municipal o estatal), sin pasar de 60 días de la apertura del CNPJ (Resolución CGSN 140/2018, art. 6º). Regla verificada el 10/10/2026.' },

    { h1: 'Conexiones con otros módulos' },
    { tabela: { colunas: ['Viene de', 'Para qué'], larguras: [3000, 6026], linhas: [
      ['Ingresos / MEI → Facturación', 'Facturación, tope, evolución de ganancias.'],
      ['Costos Variables y Costos Fijos', '"Salió", sobrante del mes y gastos que parecen personales.'],
      ['Cuentas por Pagar', 'Compromisos del mes en el Cofre.'],
      ['DAS & Obligaciones', 'Estado del DAS, DASN e impuesto a la renta en la Puntuación.'],
      ['Banco Central de Brasil (Selic)', 'Intereses del atraso en el Guardián de la Reserva.'],
    ] } },
    { p: 'La configuración guardada aquí la usan todas las pantallas del MEI (DAS, Reforma, Precios, IA Advisor MEI e Impuesto a la Renta).' },

    { h1: 'Quién puede hacer qué' },
    { p: 'Quien tiene acceso al MEI ve el panel. Guardar la configuración exige permiso de escritura en la empresa; los perfiles de solo lectura ven todo, pero la grabación es rechazada.' },

    { h1: 'Problemas comunes y soluciones' },
    { tabela: { colunas: ['Problema', 'Solución'], larguras: [3400, 5626], linhas: [
      ['La facturación no coincide con lo que vendí.', 'Revise en MEI → Facturación si algún ingreso está marcado para no contar en el tope, y si las fechas están en el año correcto.'],
      ['El tope aparece menor que R$ 81.000.', 'Es el tope proporcional del año de apertura (R$ 6.750 por mes activo). Revise la Fecha de Apertura en Configurar MEI.'],
      ['El retiro seguro es negativo.', 'El sobrante del mes no cubre DAS, impuesto a la renta y cuentas. Lo ideal es no retirar dinero hasta que la situación mejore.'],
      ['La Puntuación Fiscal está baja aunque pago el DAS.', 'Marque el DAS como pagado en DAS & Obligaciones; el panel lee ese estado.'],
      ['Error al guardar la configuración.', 'La ventana sigue abierta. Verifique que los valores sean números (con coma o punto) e intente de nuevo.'],
    ] } },
  ],
}

const doc: DocTrilingue = { pt, en, es }
export default doc
